linters:
  enable:
    - vet
    - staticcheck
    - errcheck
    - gocritic
    - ineffassign
    - unused
linters-settings:
  errcheck:
    check-blank: true
issues:
  exclude-rules:
    - path: ".*\\.pb\\.go"
      linters: [all]
