// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: volume_server.proto

package volume_server_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllocateVolumeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	VolumeId        uint32                 `protobuf:"varint,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	Collection      string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Replication     string                 `protobuf:"bytes,3,opt,name=replication,proto3" json:"replication,omitempty"`
	Ttl             string                 `protobuf:"bytes,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	DiskType        string                 `protobuf:"bytes,5,opt,name=disk_type,json=diskType,proto3" json:"disk_type,omitempty"`
	Preallocate     int64                  `protobuf:"varint,6,opt,name=preallocate,proto3" json:"preallocate,omitempty"`
	MemoryMapSizeMb uint32                 `protobuf:"varint,7,opt,name=memory_map_size_mb,json=memoryMapSizeMb,proto3" json:"memory_map_size_mb,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AllocateVolumeRequest) Reset() {
	*x = AllocateVolumeRequest{}
	mi := &file_volume_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateVolumeRequest) ProtoMessage() {}

func (x *AllocateVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volume_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateVolumeRequest.ProtoReflect.Descriptor instead.
func (*AllocateVolumeRequest) Descriptor() ([]byte, []int) {
	return file_volume_server_proto_rawDescGZIP(), []int{0}
}

func (x *AllocateVolumeRequest) GetVolumeId() uint32 {
	if x != nil {
		return x.VolumeId
	}
	return 0
}

func (x *AllocateVolumeRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *AllocateVolumeRequest) GetReplication() string {
	if x != nil {
		return x.Replication
	}
	return ""
}

func (x *AllocateVolumeRequest) GetTtl() string {
	if x != nil {
		return x.Ttl
	}
	return ""
}

func (x *AllocateVolumeRequest) GetDiskType() string {
	if x != nil {
		return x.DiskType
	}
	return ""
}

func (x *AllocateVolumeRequest) GetPreallocate() int64 {
	if x != nil {
		return x.Preallocate
	}
	return 0
}

func (x *AllocateVolumeRequest) GetMemoryMapSizeMb() uint32 {
	if x != nil {
		return x.MemoryMapSizeMb
	}
	return 0
}

type AllocateVolumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateVolumeResponse) Reset() {
	*x = AllocateVolumeResponse{}
	mi := &file_volume_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateVolumeResponse) ProtoMessage() {}

func (x *AllocateVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_volume_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateVolumeResponse.ProtoReflect.Descriptor instead.
func (*AllocateVolumeResponse) Descriptor() ([]byte, []int) {
	return file_volume_server_proto_rawDescGZIP(), []int{1}
}

func (x *AllocateVolumeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type VolumeDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      uint32                 `protobuf:"varint,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeDeleteRequest) Reset() {
	*x = VolumeDeleteRequest{}
	mi := &file_volume_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeDeleteRequest) ProtoMessage() {}

func (x *VolumeDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volume_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeDeleteRequest.ProtoReflect.Descriptor instead.
func (*VolumeDeleteRequest) Descriptor() ([]byte, []int) {
	return file_volume_server_proto_rawDescGZIP(), []int{2}
}

func (x *VolumeDeleteRequest) GetVolumeId() uint32 {
	if x != nil {
		return x.VolumeId
	}
	return 0
}

func (x *VolumeDeleteRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

type VolumeDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeDeleteResponse) Reset() {
	*x = VolumeDeleteResponse{}
	mi := &file_volume_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeDeleteResponse) ProtoMessage() {}

func (x *VolumeDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_volume_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeDeleteResponse.ProtoReflect.Descriptor instead.
func (*VolumeDeleteResponse) Descriptor() ([]byte, []int) {
	return file_volume_server_proto_rawDescGZIP(), []int{3}
}

func (x *VolumeDeleteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type VolumeCopyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VolumeId       uint32                 `protobuf:"varint,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	Collection     string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Replication    string                 `protobuf:"bytes,3,opt,name=replication,proto3" json:"replication,omitempty"`
	Ttl            string                 `protobuf:"bytes,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	SourceDataNode string                 `protobuf:"bytes,5,opt,name=source_data_node,json=sourceDataNode,proto3" json:"source_data_node,omitempty"`
	DiskType       string                 `protobuf:"bytes,6,opt,name=disk_type,json=diskType,proto3" json:"disk_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VolumeCopyRequest) Reset() {
	*x = VolumeCopyRequest{}
	mi := &file_volume_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeCopyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeCopyRequest) ProtoMessage() {}

func (x *VolumeCopyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volume_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeCopyRequest.ProtoReflect.Descriptor instead.
func (*VolumeCopyRequest) Descriptor() ([]byte, []int) {
	return file_volume_server_proto_rawDescGZIP(), []int{4}
}

func (x *VolumeCopyRequest) GetVolumeId() uint32 {
	if x != nil {
		return x.VolumeId
	}
	return 0
}

func (x *VolumeCopyRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *VolumeCopyRequest) GetReplication() string {
	if x != nil {
		return x.Replication
	}
	return ""
}

func (x *VolumeCopyRequest) GetTtl() string {
	if x != nil {
		return x.Ttl
	}
	return ""
}

func (x *VolumeCopyRequest) GetSourceDataNode() string {
	if x != nil {
		return x.SourceDataNode
	}
	return ""
}

func (x *VolumeCopyRequest) GetDiskType() string {
	if x != nil {
		return x.DiskType
	}
	return ""
}

type VolumeCopyResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProcessedBytes uint64                 `protobuf:"varint,1,opt,name=processed_bytes,json=processedBytes,proto3" json:"processed_bytes,omitempty"`
	ProcessPercent float32                `protobuf:"fixed32,2,opt,name=process_percent,json=processPercent,proto3" json:"process_percent,omitempty"`
	LastAppendAtNs string                 `protobuf:"bytes,3,opt,name=last_append_at_ns,json=lastAppendAtNs,proto3" json:"last_append_at_ns,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VolumeCopyResponse) Reset() {
	*x = VolumeCopyResponse{}
	mi := &file_volume_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeCopyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeCopyResponse) ProtoMessage() {}

func (x *VolumeCopyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_volume_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeCopyResponse.ProtoReflect.Descriptor instead.
func (*VolumeCopyResponse) Descriptor() ([]byte, []int) {
	return file_volume_server_proto_rawDescGZIP(), []int{5}
}

func (x *VolumeCopyResponse) GetProcessedBytes() uint64 {
	if x != nil {
		return x.ProcessedBytes
	}
	return 0
}

func (x *VolumeCopyResponse) GetProcessPercent() float32 {
	if x != nil {
		return x.ProcessPercent
	}
	return 0
}

func (x *VolumeCopyResponse) GetLastAppendAtNs() string {
	if x != nil {
		return x.LastAppendAtNs
	}
	return ""
}

type VolumeMarkReadonlyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      uint32                 `protobuf:"varint,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	IsReadonly    bool                   `protobuf:"varint,2,opt,name=is_readonly,json=isReadonly,proto3" json:"is_readonly,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeMarkReadonlyRequest) Reset() {
	*x = VolumeMarkReadonlyRequest{}
	mi := &file_volume_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeMarkReadonlyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeMarkReadonlyRequest) ProtoMessage() {}

func (x *VolumeMarkReadonlyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volume_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeMarkReadonlyRequest.ProtoReflect.Descriptor instead.
func (*VolumeMarkReadonlyRequest) Descriptor() ([]byte, []int) {
	return file_volume_server_proto_rawDescGZIP(), []int{6}
}

func (x *VolumeMarkReadonlyRequest) GetVolumeId() uint32 {
	if x != nil {
		return x.VolumeId
	}
	return 0
}

func (x *VolumeMarkReadonlyRequest) GetIsReadonly() bool {
	if x != nil {
		return x.IsReadonly
	}
	return false
}

type VolumeMarkReadonlyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeMarkReadonlyResponse) Reset() {
	*x = VolumeMarkReadonlyResponse{}
	mi := &file_volume_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeMarkReadonlyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeMarkReadonlyResponse) ProtoMessage() {}

func (x *VolumeMarkReadonlyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_volume_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeMarkReadonlyResponse.ProtoReflect.Descriptor instead.
func (*VolumeMarkReadonlyResponse) Descriptor() ([]byte, []int) {
	return file_volume_server_proto_rawDescGZIP(), []int{7}
}

func (x *VolumeMarkReadonlyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type VolumeStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      uint32                 `protobuf:"varint,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeStatusRequest) Reset() {
	*x = VolumeStatusRequest{}
	mi := &file_volume_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeStatusRequest) ProtoMessage() {}

func (x *VolumeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volume_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeStatusRequest.ProtoReflect.Descriptor instead.
func (*VolumeStatusRequest) Descriptor() ([]byte, []int) {
	return file_volume_server_proto_rawDescGZIP(), []int{8}
}

func (x *VolumeStatusRequest) GetVolumeId() uint32 {
	if x != nil {
		return x.VolumeId
	}
	return 0
}

type VolumeStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsReadonly    bool                   `protobuf:"varint,1,opt,name=is_readonly,json=isReadonly,proto3" json:"is_readonly,omitempty"`
	VolumeSize    uint64                 `protobuf:"varint,2,opt,name=volume_size,json=volumeSize,proto3" json:"volume_size,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeStatusResponse) Reset() {
	*x = VolumeStatusResponse{}
	mi := &file_volume_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeStatusResponse) ProtoMessage() {}

func (x *VolumeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_volume_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeStatusResponse.ProtoReflect.Descriptor instead.
func (*VolumeStatusResponse) Descriptor() ([]byte, []int) {
	return file_volume_server_proto_rawDescGZIP(), []int{9}
}

func (x *VolumeStatusResponse) GetIsReadonly() bool {
	if x != nil {
		return x.IsReadonly
	}
	return false
}

func (x *VolumeStatusResponse) GetVolumeSize() uint64 {
	if x != nil {
		return x.VolumeSize
	}
	return 0
}

func (x *VolumeStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type VolumeCompactRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	VolumeId         uint32                 `protobuf:"varint,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	GarbageThreshold float32                `protobuf:"fixed32,2,opt,name=garbage_threshold,json=garbageThreshold,proto3" json:"garbage_threshold,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VolumeCompactRequest) Reset() {
	*x = VolumeCompactRequest{}
	mi := &file_volume_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeCompactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeCompactRequest) ProtoMessage() {}

func (x *VolumeCompactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volume_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeCompactRequest.ProtoReflect.Descriptor instead.
func (*VolumeCompactRequest) Descriptor() ([]byte, []int) {
	return file_volume_server_proto_rawDescGZIP(), []int{10}
}

func (x *VolumeCompactRequest) GetVolumeId() uint32 {
	if x != nil {
		return x.VolumeId
	}
	return 0
}

func (x *VolumeCompactRequest) GetGarbageThreshold() float32 {
	if x != nil {
		return x.GarbageThreshold
	}
	return 0
}

type VolumeCompactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeCompactResponse) Reset() {
	*x = VolumeCompactResponse{}
	mi := &file_volume_server_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeCompactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeCompactResponse) ProtoMessage() {}

func (x *VolumeCompactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_volume_server_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeCompactResponse.ProtoReflect.Descriptor instead.
func (*VolumeCompactResponse) Descriptor() ([]byte, []int) {
	return file_volume_server_proto_rawDescGZIP(), []int{11}
}

func (x *VolumeCompactResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type VolumeCommitCompactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      uint32                 `protobuf:"varint,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeCommitCompactRequest) Reset() {
	*x = VolumeCommitCompactRequest{}
	mi := &file_volume_server_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeCommitCompactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeCommitCompactRequest) ProtoMessage() {}

func (x *VolumeCommitCompactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volume_server_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeCommitCompactRequest.ProtoReflect.Descriptor instead.
func (*VolumeCommitCompactRequest) Descriptor() ([]byte, []int) {
	return file_volume_server_proto_rawDescGZIP(), []int{12}
}

func (x *VolumeCommitCompactRequest) GetVolumeId() uint32 {
	if x != nil {
		return x.VolumeId
	}
	return 0
}

type VolumeCommitCompactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeCommitCompactResponse) Reset() {
	*x = VolumeCommitCompactResponse{}
	mi := &file_volume_server_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeCommitCompactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeCommitCompactResponse) ProtoMessage() {}

func (x *VolumeCommitCompactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_volume_server_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeCommitCompactResponse.ProtoReflect.Descriptor instead.
func (*VolumeCommitCompactResponse) Descriptor() ([]byte, []int) {
	return file_volume_server_proto_rawDescGZIP(), []int{13}
}

func (x *VolumeCommitCompactResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReadAllNeedlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      uint32                 `protobuf:"varint,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllNeedlesRequest) Reset() {
	*x = ReadAllNeedlesRequest{}
	mi := &file_volume_server_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllNeedlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllNeedlesRequest) ProtoMessage() {}

func (x *ReadAllNeedlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volume_server_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllNeedlesRequest.ProtoReflect.Descriptor instead.
func (*ReadAllNeedlesRequest) Descriptor() ([]byte, []int) {
	return file_volume_server_proto_rawDescGZIP(), []int{14}
}

func (x *ReadAllNeedlesRequest) GetVolumeId() uint32 {
	if x != nil {
		return x.VolumeId
	}
	return 0
}

type ReadAllNeedlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NeedleId      uint64                 `protobuf:"varint,1,opt,name=needle_id,json=needleId,proto3" json:"needle_id,omitempty"`
	Cookie        uint32                 `protobuf:"varint,2,opt,name=cookie,proto3" json:"cookie,omitempty"`
	Offset        uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Size          uint32                 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Mime          string                 `protobuf:"bytes,6,opt,name=mime,proto3" json:"mime,omitempty"`
	FileName      string                 `protobuf:"bytes,7,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,8,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllNeedlesResponse) Reset() {
	*x = ReadAllNeedlesResponse{}
	mi := &file_volume_server_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllNeedlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllNeedlesResponse) ProtoMessage() {}

func (x *ReadAllNeedlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_volume_server_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllNeedlesResponse.ProtoReflect.Descriptor instead.
func (*ReadAllNeedlesResponse) Descriptor() ([]byte, []int) {
	return file_volume_server_proto_rawDescGZIP(), []int{15}
}

func (x *ReadAllNeedlesResponse) GetNeedleId() uint64 {
	if x != nil {
		return x.NeedleId
	}
	return 0
}

func (x *ReadAllNeedlesResponse) GetCookie() uint32 {
	if x != nil {
		return x.Cookie
	}
	return 0
}

func (x *ReadAllNeedlesResponse) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadAllNeedlesResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ReadAllNeedlesResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReadAllNeedlesResponse) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *ReadAllNeedlesResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ReadAllNeedlesResponse) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

var File_volume_server_proto protoreflect.FileDescriptor

const file_volume_server_proto_rawDesc = "" +
	"\n" +
	"\x13volume_server.proto\x12\x10volume_server_pb\"\xf4\x01\n" +
	"\x15AllocateVolumeRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\rR\bvolumeId\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12 \n" +
	"\vreplication\x18\x03 \x01(\tR\vreplication\x12\x10\n" +
	"\x03ttl\x18\x04 \x01(\tR\x03ttl\x12\x1b\n" +
	"\tdisk_type\x18\x05 \x01(\tR\bdiskType\x12 \n" +
	"\vpreallocate\x18\x06 \x01(\x03R\vpreallocate\x12+\n" +
	"\x12memory_map_size_mb\x18\a \x01(\rR\x0fmemoryMapSizeMb\".\n" +
	"\x16AllocateVolumeResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"R\n" +
	"\x13VolumeDeleteRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\rR\bvolumeId\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\",\n" +
	"\x14VolumeDeleteResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\xcb\x01\n" +
	"\x11VolumeCopyRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\rR\bvolumeId\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12 \n" +
	"\vreplication\x18\x03 \x01(\tR\vreplication\x12\x10\n" +
	"\x03ttl\x18\x04 \x01(\tR\x03ttl\x12(\n" +
	"\x10source_data_node\x18\x05 \x01(\tR\x0esourceDataNode\x12\x1b\n" +
	"\tdisk_type\x18\x06 \x01(\tR\bdiskType\"\x91\x01\n" +
	"\x12VolumeCopyResponse\x12'\n" +
	"\x0fprocessed_bytes\x18\x01 \x01(\x04R\x0eprocessedBytes\x12'\n" +
	"\x0fprocess_percent\x18\x02 \x01(\x02R\x0eprocessPercent\x12)\n" +
	"\x11last_append_at_ns\x18\x03 \x01(\tR\x0elastAppendAtNs\"Y\n" +
	"\x19VolumeMarkReadonlyRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\rR\bvolumeId\x12\x1f\n" +
	"\vis_readonly\x18\x02 \x01(\bR\n" +
	"isReadonly\"2\n" +
	"\x1aVolumeMarkReadonlyResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"2\n" +
	"\x13VolumeStatusRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\rR\bvolumeId\"n\n" +
	"\x14VolumeStatusResponse\x12\x1f\n" +
	"\vis_readonly\x18\x01 \x01(\bR\n" +
	"isReadonly\x12\x1f\n" +
	"\vvolume_size\x18\x02 \x01(\x04R\n" +
	"volumeSize\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"`\n" +
	"\x14VolumeCompactRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\rR\bvolumeId\x12+\n" +
	"\x11garbage_threshold\x18\x02 \x01(\x02R\x10garbageThreshold\"-\n" +
	"\x15VolumeCompactResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"9\n" +
	"\x1aVolumeCommitCompactRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\rR\bvolumeId\"3\n" +
	"\x1bVolumeCommitCompactResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"4\n" +
	"\x15ReadAllNeedlesRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\rR\bvolumeId\"\xdd\x01\n" +
	"\x16ReadAllNeedlesResponse\x12\x1b\n" +
	"\tneedle_id\x18\x01 \x01(\x04R\bneedleId\x12\x16\n" +
	"\x06cookie\x18\x02 \x01(\rR\x06cookie\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\x12\x12\n" +
	"\x04size\x18\x04 \x01(\rR\x04size\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12\x12\n" +
	"\x04mime\x18\x06 \x01(\tR\x04mime\x12\x1b\n" +
	"\tfile_name\x18\a \x01(\tR\bfileName\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\b \x01(\bR\tisDeleted2\xca\x06\n" +
	"\fVolumeServer\x12e\n" +
	"\x0eAllocateVolume\x12'.volume_server_pb.AllocateVolumeRequest\x1a(.volume_server_pb.AllocateVolumeResponse\"\x00\x12_\n" +
	"\fVolumeDelete\x12%.volume_server_pb.VolumeDeleteRequest\x1a&.volume_server_pb.VolumeDeleteResponse\"\x00\x12[\n" +
	"\n" +
	"VolumeCopy\x12#.volume_server_pb.VolumeCopyRequest\x1a$.volume_server_pb.VolumeCopyResponse\"\x000\x01\x12q\n" +
	"\x12VolumeMarkReadonly\x12+.volume_server_pb.VolumeMarkReadonlyRequest\x1a,.volume_server_pb.VolumeMarkReadonlyResponse\"\x00\x12_\n" +
	"\fVolumeStatus\x12%.volume_server_pb.VolumeStatusRequest\x1a&.volume_server_pb.VolumeStatusResponse\"\x00\x12b\n" +
	"\rVolumeCompact\x12&.volume_server_pb.VolumeCompactRequest\x1a'.volume_server_pb.VolumeCompactResponse\"\x00\x12t\n" +
	"\x13VolumeCommitCompact\x12,.volume_server_pb.VolumeCommitCompactRequest\x1a-.volume_server_pb.VolumeCommitCompactResponse\"\x00\x12g\n" +
	"\x0eReadAllNeedles\x12'.volume_server_pb.ReadAllNeedlesRequest\x1a(.volume_server_pb.ReadAllNeedlesResponse\"\x000\x01B\x1cZ\x1agoblob/pb/volume_server_pbb\x06proto3"

var (
	file_volume_server_proto_rawDescOnce sync.Once
	file_volume_server_proto_rawDescData []byte
)

func file_volume_server_proto_rawDescGZIP() []byte {
	file_volume_server_proto_rawDescOnce.Do(func() {
		file_volume_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_volume_server_proto_rawDesc), len(file_volume_server_proto_rawDesc)))
	})
	return file_volume_server_proto_rawDescData
}

var file_volume_server_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_volume_server_proto_goTypes = []any{
	(*AllocateVolumeRequest)(nil),       // 0: volume_server_pb.AllocateVolumeRequest
	(*AllocateVolumeResponse)(nil),      // 1: volume_server_pb.AllocateVolumeResponse
	(*VolumeDeleteRequest)(nil),         // 2: volume_server_pb.VolumeDeleteRequest
	(*VolumeDeleteResponse)(nil),        // 3: volume_server_pb.VolumeDeleteResponse
	(*VolumeCopyRequest)(nil),           // 4: volume_server_pb.VolumeCopyRequest
	(*VolumeCopyResponse)(nil),          // 5: volume_server_pb.VolumeCopyResponse
	(*VolumeMarkReadonlyRequest)(nil),   // 6: volume_server_pb.VolumeMarkReadonlyRequest
	(*VolumeMarkReadonlyResponse)(nil),  // 7: volume_server_pb.VolumeMarkReadonlyResponse
	(*VolumeStatusRequest)(nil),         // 8: volume_server_pb.VolumeStatusRequest
	(*VolumeStatusResponse)(nil),        // 9: volume_server_pb.VolumeStatusResponse
	(*VolumeCompactRequest)(nil),        // 10: volume_server_pb.VolumeCompactRequest
	(*VolumeCompactResponse)(nil),       // 11: volume_server_pb.VolumeCompactResponse
	(*VolumeCommitCompactRequest)(nil),  // 12: volume_server_pb.VolumeCommitCompactRequest
	(*VolumeCommitCompactResponse)(nil), // 13: volume_server_pb.VolumeCommitCompactResponse
	(*ReadAllNeedlesRequest)(nil),       // 14: volume_server_pb.ReadAllNeedlesRequest
	(*ReadAllNeedlesResponse)(nil),      // 15: volume_server_pb.ReadAllNeedlesResponse
}
var file_volume_server_proto_depIdxs = []int32{
	0,  // 0: volume_server_pb.VolumeServer.AllocateVolume:input_type -> volume_server_pb.AllocateVolumeRequest
	2,  // 1: volume_server_pb.VolumeServer.VolumeDelete:input_type -> volume_server_pb.VolumeDeleteRequest
	4,  // 2: volume_server_pb.VolumeServer.VolumeCopy:input_type -> volume_server_pb.VolumeCopyRequest
	6,  // 3: volume_server_pb.VolumeServer.VolumeMarkReadonly:input_type -> volume_server_pb.VolumeMarkReadonlyRequest
	8,  // 4: volume_server_pb.VolumeServer.VolumeStatus:input_type -> volume_server_pb.VolumeStatusRequest
	10, // 5: volume_server_pb.VolumeServer.VolumeCompact:input_type -> volume_server_pb.VolumeCompactRequest
	12, // 6: volume_server_pb.VolumeServer.VolumeCommitCompact:input_type -> volume_server_pb.VolumeCommitCompactRequest
	14, // 7: volume_server_pb.VolumeServer.ReadAllNeedles:input_type -> volume_server_pb.ReadAllNeedlesRequest
	1,  // 8: volume_server_pb.VolumeServer.AllocateVolume:output_type -> volume_server_pb.AllocateVolumeResponse
	3,  // 9: volume_server_pb.VolumeServer.VolumeDelete:output_type -> volume_server_pb.VolumeDeleteResponse
	5,  // 10: volume_server_pb.VolumeServer.VolumeCopy:output_type -> volume_server_pb.VolumeCopyResponse
	7,  // 11: volume_server_pb.VolumeServer.VolumeMarkReadonly:output_type -> volume_server_pb.VolumeMarkReadonlyResponse
	9,  // 12: volume_server_pb.VolumeServer.VolumeStatus:output_type -> volume_server_pb.VolumeStatusResponse
	11, // 13: volume_server_pb.VolumeServer.VolumeCompact:output_type -> volume_server_pb.VolumeCompactResponse
	13, // 14: volume_server_pb.VolumeServer.VolumeCommitCompact:output_type -> volume_server_pb.VolumeCommitCompactResponse
	15, // 15: volume_server_pb.VolumeServer.ReadAllNeedles:output_type -> volume_server_pb.ReadAllNeedlesResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_volume_server_proto_init() }
func file_volume_server_proto_init() {
	if File_volume_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_volume_server_proto_rawDesc), len(file_volume_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_volume_server_proto_goTypes,
		DependencyIndexes: file_volume_server_proto_depIdxs,
		MessageInfos:      file_volume_server_proto_msgTypes,
	}.Build()
	File_volume_server_proto = out.File
	file_volume_server_proto_goTypes = nil
	file_volume_server_proto_depIdxs = nil
}
