// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: master.proto

package master_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Heartbeat struct {
	state           protoimpl.MessageState      `protogen:"open.v1"`
	Ip              string                      `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port            uint32                      `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	PublicUrl       string                      `protobuf:"bytes,3,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"`
	GrpcPort        uint32                      `protobuf:"varint,4,opt,name=grpc_port,json=grpcPort,proto3" json:"grpc_port,omitempty"`
	MaxFileKey      uint64                      `protobuf:"varint,5,opt,name=max_file_key,json=maxFileKey,proto3" json:"max_file_key,omitempty"`
	DataCenter      string                      `protobuf:"bytes,6,opt,name=data_center,json=dataCenter,proto3" json:"data_center,omitempty"`
	Rack            string                      `protobuf:"bytes,7,opt,name=rack,proto3" json:"rack,omitempty"`
	AdminPort       uint32                      `protobuf:"varint,8,opt,name=admin_port,json=adminPort,proto3" json:"admin_port,omitempty"`
	Volumes         []*VolumeInformationMessage `protobuf:"bytes,9,rep,name=volumes,proto3" json:"volumes,omitempty"`
	DeletedVids     []uint32                    `protobuf:"varint,11,rep,packed,name=deleted_vids,json=deletedVids,proto3" json:"deleted_vids,omitempty"`
	NewVids         []uint32                    `protobuf:"varint,12,rep,packed,name=new_vids,json=newVids,proto3" json:"new_vids,omitempty"`
	MaxVolumeCounts []*MaxVolumeCounts          `protobuf:"bytes,13,rep,name=max_volume_counts,json=maxVolumeCounts,proto3" json:"max_volume_counts,omitempty"`
	HasNoVolumes    bool                        `protobuf:"varint,14,opt,name=has_no_volumes,json=hasNoVolumes,proto3" json:"has_no_volumes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_master_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{0}
}

func (x *Heartbeat) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Heartbeat) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Heartbeat) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

func (x *Heartbeat) GetGrpcPort() uint32 {
	if x != nil {
		return x.GrpcPort
	}
	return 0
}

func (x *Heartbeat) GetMaxFileKey() uint64 {
	if x != nil {
		return x.MaxFileKey
	}
	return 0
}

func (x *Heartbeat) GetDataCenter() string {
	if x != nil {
		return x.DataCenter
	}
	return ""
}

func (x *Heartbeat) GetRack() string {
	if x != nil {
		return x.Rack
	}
	return ""
}

func (x *Heartbeat) GetAdminPort() uint32 {
	if x != nil {
		return x.AdminPort
	}
	return 0
}

func (x *Heartbeat) GetVolumes() []*VolumeInformationMessage {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *Heartbeat) GetDeletedVids() []uint32 {
	if x != nil {
		return x.DeletedVids
	}
	return nil
}

func (x *Heartbeat) GetNewVids() []uint32 {
	if x != nil {
		return x.NewVids
	}
	return nil
}

func (x *Heartbeat) GetMaxVolumeCounts() []*MaxVolumeCounts {
	if x != nil {
		return x.MaxVolumeCounts
	}
	return nil
}

func (x *Heartbeat) GetHasNoVolumes() bool {
	if x != nil {
		return x.HasNoVolumes
	}
	return false
}

type MaxVolumeCounts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiskType      string                 `protobuf:"bytes,1,opt,name=disk_type,json=diskType,proto3" json:"disk_type,omitempty"`
	MaxCount      uint32                 `protobuf:"varint,2,opt,name=max_count,json=maxCount,proto3" json:"max_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaxVolumeCounts) Reset() {
	*x = MaxVolumeCounts{}
	mi := &file_master_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaxVolumeCounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxVolumeCounts) ProtoMessage() {}

func (x *MaxVolumeCounts) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxVolumeCounts.ProtoReflect.Descriptor instead.
func (*MaxVolumeCounts) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{1}
}

func (x *MaxVolumeCounts) GetDiskType() string {
	if x != nil {
		return x.DiskType
	}
	return ""
}

func (x *MaxVolumeCounts) GetMaxCount() uint32 {
	if x != nil {
		return x.MaxCount
	}
	return 0
}

type HeartbeatResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	VolumeSizeLimit  uint64                 `protobuf:"varint,1,opt,name=volume_size_limit,json=volumeSizeLimit,proto3" json:"volume_size_limit,omitempty"`
	Leader           string                 `protobuf:"bytes,2,opt,name=leader,proto3" json:"leader,omitempty"`
	MetricsAddress   string                 `protobuf:"bytes,3,opt,name=metrics_address,json=metricsAddress,proto3" json:"metrics_address,omitempty"`
	DeletedVolumeIds []uint32               `protobuf:"varint,4,rep,packed,name=deleted_volume_ids,json=deletedVolumeIds,proto3" json:"deleted_volume_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_master_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatResponse) GetVolumeSizeLimit() uint64 {
	if x != nil {
		return x.VolumeSizeLimit
	}
	return 0
}

func (x *HeartbeatResponse) GetLeader() string {
	if x != nil {
		return x.Leader
	}
	return ""
}

func (x *HeartbeatResponse) GetMetricsAddress() string {
	if x != nil {
		return x.MetricsAddress
	}
	return ""
}

func (x *HeartbeatResponse) GetDeletedVolumeIds() []uint32 {
	if x != nil {
		return x.DeletedVolumeIds
	}
	return nil
}

type VolumeInformationMessage struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Size               uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Collection         string                 `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	FileCount          uint64                 `protobuf:"varint,4,opt,name=file_count,json=fileCount,proto3" json:"file_count,omitempty"`
	DeleteCount        uint64                 `protobuf:"varint,5,opt,name=delete_count,json=deleteCount,proto3" json:"delete_count,omitempty"`
	DeletedByteCount   uint64                 `protobuf:"varint,6,opt,name=deleted_byte_count,json=deletedByteCount,proto3" json:"deleted_byte_count,omitempty"`
	ReadOnly           bool                   `protobuf:"varint,7,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	ReplicaPlacement   uint32                 `protobuf:"varint,8,opt,name=replica_placement,json=replicaPlacement,proto3" json:"replica_placement,omitempty"`
	Ttl                string                 `protobuf:"bytes,9,opt,name=ttl,proto3" json:"ttl,omitempty"`
	CompactionRevision uint32                 `protobuf:"varint,10,opt,name=compaction_revision,json=compactionRevision,proto3" json:"compaction_revision,omitempty"`
	DiskType           string                 `protobuf:"bytes,11,opt,name=disk_type,json=diskType,proto3" json:"disk_type,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VolumeInformationMessage) Reset() {
	*x = VolumeInformationMessage{}
	mi := &file_master_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeInformationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeInformationMessage) ProtoMessage() {}

func (x *VolumeInformationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeInformationMessage.ProtoReflect.Descriptor instead.
func (*VolumeInformationMessage) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{3}
}

func (x *VolumeInformationMessage) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VolumeInformationMessage) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *VolumeInformationMessage) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *VolumeInformationMessage) GetFileCount() uint64 {
	if x != nil {
		return x.FileCount
	}
	return 0
}

func (x *VolumeInformationMessage) GetDeleteCount() uint64 {
	if x != nil {
		return x.DeleteCount
	}
	return 0
}

func (x *VolumeInformationMessage) GetDeletedByteCount() uint64 {
	if x != nil {
		return x.DeletedByteCount
	}
	return 0
}

func (x *VolumeInformationMessage) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *VolumeInformationMessage) GetReplicaPlacement() uint32 {
	if x != nil {
		return x.ReplicaPlacement
	}
	return 0
}

func (x *VolumeInformationMessage) GetTtl() string {
	if x != nil {
		return x.Ttl
	}
	return ""
}

func (x *VolumeInformationMessage) GetCompactionRevision() uint32 {
	if x != nil {
		return x.CompactionRevision
	}
	return 0
}

func (x *VolumeInformationMessage) GetDiskType() string {
	if x != nil {
		return x.DiskType
	}
	return ""
}

type KeepConnectedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientType    string                 `protobuf:"bytes,1,opt,name=client_type,json=clientType,proto3" json:"client_type,omitempty"`
	ClientAddress string                 `protobuf:"bytes,2,opt,name=client_address,json=clientAddress,proto3" json:"client_address,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	FilerGroup    string                 `protobuf:"bytes,4,opt,name=filer_group,json=filerGroup,proto3" json:"filer_group,omitempty"`
	DataCenter    string                 `protobuf:"bytes,5,opt,name=data_center,json=dataCenter,proto3" json:"data_center,omitempty"`
	Rack          string                 `protobuf:"bytes,6,opt,name=rack,proto3" json:"rack,omitempty"`
	GrpcPort      string                 `protobuf:"bytes,7,opt,name=grpc_port,json=grpcPort,proto3" json:"grpc_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepConnectedRequest) Reset() {
	*x = KeepConnectedRequest{}
	mi := &file_master_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepConnectedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepConnectedRequest) ProtoMessage() {}

func (x *KeepConnectedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepConnectedRequest.ProtoReflect.Descriptor instead.
func (*KeepConnectedRequest) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{4}
}

func (x *KeepConnectedRequest) GetClientType() string {
	if x != nil {
		return x.ClientType
	}
	return ""
}

func (x *KeepConnectedRequest) GetClientAddress() string {
	if x != nil {
		return x.ClientAddress
	}
	return ""
}

func (x *KeepConnectedRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *KeepConnectedRequest) GetFilerGroup() string {
	if x != nil {
		return x.FilerGroup
	}
	return ""
}

func (x *KeepConnectedRequest) GetDataCenter() string {
	if x != nil {
		return x.DataCenter
	}
	return ""
}

func (x *KeepConnectedRequest) GetRack() string {
	if x != nil {
		return x.Rack
	}
	return ""
}

func (x *KeepConnectedRequest) GetGrpcPort() string {
	if x != nil {
		return x.GrpcPort
	}
	return ""
}

type KeepConnectedResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	VolumeLocations []*VolumeLocation      `protobuf:"bytes,1,rep,name=volume_locations,json=volumeLocations,proto3" json:"volume_locations,omitempty"`
	MetricsAddress  string                 `protobuf:"bytes,2,opt,name=metrics_address,json=metricsAddress,proto3" json:"metrics_address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *KeepConnectedResponse) Reset() {
	*x = KeepConnectedResponse{}
	mi := &file_master_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepConnectedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepConnectedResponse) ProtoMessage() {}

func (x *KeepConnectedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepConnectedResponse.ProtoReflect.Descriptor instead.
func (*KeepConnectedResponse) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{5}
}

func (x *KeepConnectedResponse) GetVolumeLocations() []*VolumeLocation {
	if x != nil {
		return x.VolumeLocations
	}
	return nil
}

func (x *KeepConnectedResponse) GetMetricsAddress() string {
	if x != nil {
		return x.MetricsAddress
	}
	return ""
}

type VolumeLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	PublicUrl     string                 `protobuf:"bytes,2,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"`
	NewVids       []uint32               `protobuf:"varint,3,rep,packed,name=new_vids,json=newVids,proto3" json:"new_vids,omitempty"`
	DeletedVids   []uint32               `protobuf:"varint,4,rep,packed,name=deleted_vids,json=deletedVids,proto3" json:"deleted_vids,omitempty"`
	Leader        string                 `protobuf:"bytes,5,opt,name=leader,proto3" json:"leader,omitempty"`
	DataCenter    string                 `protobuf:"bytes,6,opt,name=data_center,json=dataCenter,proto3" json:"data_center,omitempty"`
	Rack          string                 `protobuf:"bytes,7,opt,name=rack,proto3" json:"rack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeLocation) Reset() {
	*x = VolumeLocation{}
	mi := &file_master_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeLocation) ProtoMessage() {}

func (x *VolumeLocation) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeLocation.ProtoReflect.Descriptor instead.
func (*VolumeLocation) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{6}
}

func (x *VolumeLocation) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *VolumeLocation) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

func (x *VolumeLocation) GetNewVids() []uint32 {
	if x != nil {
		return x.NewVids
	}
	return nil
}

func (x *VolumeLocation) GetDeletedVids() []uint32 {
	if x != nil {
		return x.DeletedVids
	}
	return nil
}

func (x *VolumeLocation) GetLeader() string {
	if x != nil {
		return x.Leader
	}
	return ""
}

func (x *VolumeLocation) GetDataCenter() string {
	if x != nil {
		return x.DataCenter
	}
	return ""
}

func (x *VolumeLocation) GetRack() string {
	if x != nil {
		return x.Rack
	}
	return ""
}

type AssignRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Count               uint64                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Replication         string                 `protobuf:"bytes,2,opt,name=replication,proto3" json:"replication,omitempty"`
	Collection          string                 `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	Ttl                 string                 `protobuf:"bytes,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	DataCenter          string                 `protobuf:"bytes,5,opt,name=data_center,json=dataCenter,proto3" json:"data_center,omitempty"`
	Rack                string                 `protobuf:"bytes,6,opt,name=rack,proto3" json:"rack,omitempty"`
	DiskType            string                 `protobuf:"bytes,7,opt,name=disk_type,json=diskType,proto3" json:"disk_type,omitempty"`
	Preallocate         int64                  `protobuf:"varint,8,opt,name=preallocate,proto3" json:"preallocate,omitempty"`
	WritableVolumeCount string                 `protobuf:"bytes,9,opt,name=writable_volume_count,json=writableVolumeCount,proto3" json:"writable_volume_count,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AssignRequest) Reset() {
	*x = AssignRequest{}
	mi := &file_master_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRequest) ProtoMessage() {}

func (x *AssignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRequest.ProtoReflect.Descriptor instead.
func (*AssignRequest) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{7}
}

func (x *AssignRequest) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AssignRequest) GetReplication() string {
	if x != nil {
		return x.Replication
	}
	return ""
}

func (x *AssignRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *AssignRequest) GetTtl() string {
	if x != nil {
		return x.Ttl
	}
	return ""
}

func (x *AssignRequest) GetDataCenter() string {
	if x != nil {
		return x.DataCenter
	}
	return ""
}

func (x *AssignRequest) GetRack() string {
	if x != nil {
		return x.Rack
	}
	return ""
}

func (x *AssignRequest) GetDiskType() string {
	if x != nil {
		return x.DiskType
	}
	return ""
}

func (x *AssignRequest) GetPreallocate() int64 {
	if x != nil {
		return x.Preallocate
	}
	return 0
}

func (x *AssignRequest) GetWritableVolumeCount() string {
	if x != nil {
		return x.WritableVolumeCount
	}
	return ""
}

type AssignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fid           string                 `protobuf:"bytes,1,opt,name=fid,proto3" json:"fid,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	PublicUrl     string                 `protobuf:"bytes,3,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"`
	Count         uint64                 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	Auth          string                 `protobuf:"bytes,6,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignResponse) Reset() {
	*x = AssignResponse{}
	mi := &file_master_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignResponse) ProtoMessage() {}

func (x *AssignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignResponse.ProtoReflect.Descriptor instead.
func (*AssignResponse) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{8}
}

func (x *AssignResponse) GetFid() string {
	if x != nil {
		return x.Fid
	}
	return ""
}

func (x *AssignResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AssignResponse) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

func (x *AssignResponse) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AssignResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AssignResponse) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

type LookupVolumeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	VolumeOrFileIds []string               `protobuf:"bytes,1,rep,name=volume_or_file_ids,json=volumeOrFileIds,proto3" json:"volume_or_file_ids,omitempty"`
	Collection      string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LookupVolumeRequest) Reset() {
	*x = LookupVolumeRequest{}
	mi := &file_master_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupVolumeRequest) ProtoMessage() {}

func (x *LookupVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupVolumeRequest.ProtoReflect.Descriptor instead.
func (*LookupVolumeRequest) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{9}
}

func (x *LookupVolumeRequest) GetVolumeOrFileIds() []string {
	if x != nil {
		return x.VolumeOrFileIds
	}
	return nil
}

func (x *LookupVolumeRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

type LookupVolumeResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	LocationsMap  map[string]*VolumeIdLocations `protobuf:"bytes,1,rep,name=locations_map,json=locationsMap,proto3" json:"locations_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupVolumeResponse) Reset() {
	*x = LookupVolumeResponse{}
	mi := &file_master_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupVolumeResponse) ProtoMessage() {}

func (x *LookupVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupVolumeResponse.ProtoReflect.Descriptor instead.
func (*LookupVolumeResponse) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{10}
}

func (x *LookupVolumeResponse) GetLocationsMap() map[string]*VolumeIdLocations {
	if x != nil {
		return x.LocationsMap
	}
	return nil
}

type VolumeIdLocations struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locations     []*Location            `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeIdLocations) Reset() {
	*x = VolumeIdLocations{}
	mi := &file_master_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeIdLocations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeIdLocations) ProtoMessage() {}

func (x *VolumeIdLocations) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeIdLocations.ProtoReflect.Descriptor instead.
func (*VolumeIdLocations) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{11}
}

func (x *VolumeIdLocations) GetLocations() []*Location {
	if x != nil {
		return x.Locations
	}
	return nil
}

func (x *VolumeIdLocations) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	PublicUrl     string                 `protobuf:"bytes,2,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"`
	DataCenter    string                 `protobuf:"bytes,3,opt,name=data_center,json=dataCenter,proto3" json:"data_center,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_master_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{12}
}

func (x *Location) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Location) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

func (x *Location) GetDataCenter() string {
	if x != nil {
		return x.DataCenter
	}
	return ""
}

type GetMasterConfigurationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMasterConfigurationRequest) Reset() {
	*x = GetMasterConfigurationRequest{}
	mi := &file_master_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMasterConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMasterConfigurationRequest) ProtoMessage() {}

func (x *GetMasterConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMasterConfigurationRequest.ProtoReflect.Descriptor instead.
func (*GetMasterConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{13}
}

type GetMasterConfigurationResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MetricsAddress     string                 `protobuf:"bytes,1,opt,name=metrics_address,json=metricsAddress,proto3" json:"metrics_address,omitempty"`
	Leader             string                 `protobuf:"bytes,2,opt,name=leader,proto3" json:"leader,omitempty"`
	VolumeSizeLimit    uint64                 `protobuf:"varint,3,opt,name=volume_size_limit,json=volumeSizeLimit,proto3" json:"volume_size_limit,omitempty"`
	DefaultReplication string                 `protobuf:"bytes,4,opt,name=default_replication,json=defaultReplication,proto3" json:"default_replication,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetMasterConfigurationResponse) Reset() {
	*x = GetMasterConfigurationResponse{}
	mi := &file_master_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMasterConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMasterConfigurationResponse) ProtoMessage() {}

func (x *GetMasterConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMasterConfigurationResponse.ProtoReflect.Descriptor instead.
func (*GetMasterConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{14}
}

func (x *GetMasterConfigurationResponse) GetMetricsAddress() string {
	if x != nil {
		return x.MetricsAddress
	}
	return ""
}

func (x *GetMasterConfigurationResponse) GetLeader() string {
	if x != nil {
		return x.Leader
	}
	return ""
}

func (x *GetMasterConfigurationResponse) GetVolumeSizeLimit() uint64 {
	if x != nil {
		return x.VolumeSizeLimit
	}
	return 0
}

func (x *GetMasterConfigurationResponse) GetDefaultReplication() string {
	if x != nil {
		return x.DefaultReplication
	}
	return ""
}

type VolumeListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeListRequest) Reset() {
	*x = VolumeListRequest{}
	mi := &file_master_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeListRequest) ProtoMessage() {}

func (x *VolumeListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeListRequest.ProtoReflect.Descriptor instead.
func (*VolumeListRequest) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{15}
}

type VolumeListResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TopologyInfo    *TopologyInfo          `protobuf:"bytes,1,opt,name=topology_info,json=topologyInfo,proto3" json:"topology_info,omitempty"`
	VolumeSizeLimit uint64                 `protobuf:"varint,2,opt,name=volume_size_limit,json=volumeSizeLimit,proto3" json:"volume_size_limit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VolumeListResponse) Reset() {
	*x = VolumeListResponse{}
	mi := &file_master_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeListResponse) ProtoMessage() {}

func (x *VolumeListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeListResponse.ProtoReflect.Descriptor instead.
func (*VolumeListResponse) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{16}
}

func (x *VolumeListResponse) GetTopologyInfo() *TopologyInfo {
	if x != nil {
		return x.TopologyInfo
	}
	return nil
}

func (x *VolumeListResponse) GetVolumeSizeLimit() uint64 {
	if x != nil {
		return x.VolumeSizeLimit
	}
	return 0
}

type TopologyInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DataCenterInfos []*DataCenterInfo      `protobuf:"bytes,2,rep,name=data_center_infos,json=dataCenterInfos,proto3" json:"data_center_infos,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TopologyInfo) Reset() {
	*x = TopologyInfo{}
	mi := &file_master_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyInfo) ProtoMessage() {}

func (x *TopologyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyInfo.ProtoReflect.Descriptor instead.
func (*TopologyInfo) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{17}
}

func (x *TopologyInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TopologyInfo) GetDataCenterInfos() []*DataCenterInfo {
	if x != nil {
		return x.DataCenterInfos
	}
	return nil
}

type DataCenterInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RackInfos     []*RackInfo            `protobuf:"bytes,2,rep,name=rack_infos,json=rackInfos,proto3" json:"rack_infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataCenterInfo) Reset() {
	*x = DataCenterInfo{}
	mi := &file_master_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataCenterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataCenterInfo) ProtoMessage() {}

func (x *DataCenterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataCenterInfo.ProtoReflect.Descriptor instead.
func (*DataCenterInfo) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{18}
}

func (x *DataCenterInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataCenterInfo) GetRackInfos() []*RackInfo {
	if x != nil {
		return x.RackInfos
	}
	return nil
}

type RackInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DataNodeInfos []*DataNodeInfo        `protobuf:"bytes,2,rep,name=data_node_infos,json=dataNodeInfos,proto3" json:"data_node_infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RackInfo) Reset() {
	*x = RackInfo{}
	mi := &file_master_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RackInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RackInfo) ProtoMessage() {}

func (x *RackInfo) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RackInfo.ProtoReflect.Descriptor instead.
func (*RackInfo) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{19}
}

func (x *RackInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RackInfo) GetDataNodeInfos() []*DataNodeInfo {
	if x != nil {
		return x.DataNodeInfos
	}
	return nil
}

type DataNodeInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PublicUrl         string                 `protobuf:"bytes,2,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"`
	FreeVolumeCount   uint64                 `protobuf:"varint,3,opt,name=free_volume_count,json=freeVolumeCount,proto3" json:"free_volume_count,omitempty"`
	ActiveVolumeCount uint64                 `protobuf:"varint,4,opt,name=active_volume_count,json=activeVolumeCount,proto3" json:"active_volume_count,omitempty"`
	RemoteVolumeCount uint64                 `protobuf:"varint,5,opt,name=remote_volume_count,json=remoteVolumeCount,proto3" json:"remote_volume_count,omitempty"`
	DiskInfos         []*DiskInfo            `protobuf:"bytes,6,rep,name=disk_infos,json=diskInfos,proto3" json:"disk_infos,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DataNodeInfo) Reset() {
	*x = DataNodeInfo{}
	mi := &file_master_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataNodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataNodeInfo) ProtoMessage() {}

func (x *DataNodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataNodeInfo.ProtoReflect.Descriptor instead.
func (*DataNodeInfo) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{20}
}

func (x *DataNodeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataNodeInfo) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

func (x *DataNodeInfo) GetFreeVolumeCount() uint64 {
	if x != nil {
		return x.FreeVolumeCount
	}
	return 0
}

func (x *DataNodeInfo) GetActiveVolumeCount() uint64 {
	if x != nil {
		return x.ActiveVolumeCount
	}
	return 0
}

func (x *DataNodeInfo) GetRemoteVolumeCount() uint64 {
	if x != nil {
		return x.RemoteVolumeCount
	}
	return 0
}

func (x *DataNodeInfo) GetDiskInfos() []*DiskInfo {
	if x != nil {
		return x.DiskInfos
	}
	return nil
}

type DiskInfo struct {
	state           protoimpl.MessageState      `protogen:"open.v1"`
	Type            string                      `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	VolumeInfos     []*VolumeInformationMessage `protobuf:"bytes,2,rep,name=volume_infos,json=volumeInfos,proto3" json:"volume_infos,omitempty"`
	MaxVolumeCount  uint64                      `protobuf:"varint,3,opt,name=max_volume_count,json=maxVolumeCount,proto3" json:"max_volume_count,omitempty"`
	FreeVolumeCount uint64                      `protobuf:"varint,4,opt,name=free_volume_count,json=freeVolumeCount,proto3" json:"free_volume_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DiskInfo) Reset() {
	*x = DiskInfo{}
	mi := &file_master_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskInfo) ProtoMessage() {}

func (x *DiskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_master_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskInfo.ProtoReflect.Descriptor instead.
func (*DiskInfo) Descriptor() ([]byte, []int) {
	return file_master_proto_rawDescGZIP(), []int{21}
}

func (x *DiskInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DiskInfo) GetVolumeInfos() []*VolumeInformationMessage {
	if x != nil {
		return x.VolumeInfos
	}
	return nil
}

func (x *DiskInfo) GetMaxVolumeCount() uint64 {
	if x != nil {
		return x.MaxVolumeCount
	}
	return 0
}

func (x *DiskInfo) GetFreeVolumeCount() uint64 {
	if x != nil {
		return x.FreeVolumeCount
	}
	return 0
}

var File_master_proto protoreflect.FileDescriptor

const file_master_proto_rawDesc = "" +
	"\n" +
	"\fmaster.proto\x12\tmaster_pb\"\xcc\x03\n" +
	"\tHeartbeat\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x1d\n" +
	"\n" +
	"public_url\x18\x03 \x01(\tR\tpublicUrl\x12\x1b\n" +
	"\tgrpc_port\x18\x04 \x01(\rR\bgrpcPort\x12 \n" +
	"\fmax_file_key\x18\x05 \x01(\x04R\n" +
	"maxFileKey\x12\x1f\n" +
	"\vdata_center\x18\x06 \x01(\tR\n" +
	"dataCenter\x12\x12\n" +
	"\x04rack\x18\a \x01(\tR\x04rack\x12\x1d\n" +
	"\n" +
	"admin_port\x18\b \x01(\rR\tadminPort\x12=\n" +
	"\avolumes\x18\t \x03(\v2#.master_pb.VolumeInformationMessageR\avolumes\x12!\n" +
	"\fdeleted_vids\x18\v \x03(\rR\vdeletedVids\x12\x19\n" +
	"\bnew_vids\x18\f \x03(\rR\anewVids\x12F\n" +
	"\x11max_volume_counts\x18\r \x03(\v2\x1a.master_pb.MaxVolumeCountsR\x0fmaxVolumeCounts\x12$\n" +
	"\x0ehas_no_volumes\x18\x0e \x01(\bR\fhasNoVolumes\"K\n" +
	"\x0fMaxVolumeCounts\x12\x1b\n" +
	"\tdisk_type\x18\x01 \x01(\tR\bdiskType\x12\x1b\n" +
	"\tmax_count\x18\x02 \x01(\rR\bmaxCount\"\xae\x01\n" +
	"\x11HeartbeatResponse\x12*\n" +
	"\x11volume_size_limit\x18\x01 \x01(\x04R\x0fvolumeSizeLimit\x12\x16\n" +
	"\x06leader\x18\x02 \x01(\tR\x06leader\x12'\n" +
	"\x0fmetrics_address\x18\x03 \x01(\tR\x0emetricsAddress\x12,\n" +
	"\x12deleted_volume_ids\x18\x04 \x03(\rR\x10deletedVolumeIds\"\xf8\x02\n" +
	"\x18VolumeInformationMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x12\x1e\n" +
	"\n" +
	"collection\x18\x03 \x01(\tR\n" +
	"collection\x12\x1d\n" +
	"\n" +
	"file_count\x18\x04 \x01(\x04R\tfileCount\x12!\n" +
	"\fdelete_count\x18\x05 \x01(\x04R\vdeleteCount\x12,\n" +
	"\x12deleted_byte_count\x18\x06 \x01(\x04R\x10deletedByteCount\x12\x1b\n" +
	"\tread_only\x18\a \x01(\bR\breadOnly\x12+\n" +
	"\x11replica_placement\x18\b \x01(\rR\x10replicaPlacement\x12\x10\n" +
	"\x03ttl\x18\t \x01(\tR\x03ttl\x12/\n" +
	"\x13compaction_revision\x18\n" +
	" \x01(\rR\x12compactionRevision\x12\x1b\n" +
	"\tdisk_type\x18\v \x01(\tR\bdiskType\"\xeb\x01\n" +
	"\x14KeepConnectedRequest\x12\x1f\n" +
	"\vclient_type\x18\x01 \x01(\tR\n" +
	"clientType\x12%\n" +
	"\x0eclient_address\x18\x02 \x01(\tR\rclientAddress\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1f\n" +
	"\vfiler_group\x18\x04 \x01(\tR\n" +
	"filerGroup\x12\x1f\n" +
	"\vdata_center\x18\x05 \x01(\tR\n" +
	"dataCenter\x12\x12\n" +
	"\x04rack\x18\x06 \x01(\tR\x04rack\x12\x1b\n" +
	"\tgrpc_port\x18\a \x01(\tR\bgrpcPort\"\x86\x01\n" +
	"\x15KeepConnectedResponse\x12D\n" +
	"\x10volume_locations\x18\x01 \x03(\v2\x19.master_pb.VolumeLocationR\x0fvolumeLocations\x12'\n" +
	"\x0fmetrics_address\x18\x02 \x01(\tR\x0emetricsAddress\"\xcc\x01\n" +
	"\x0eVolumeLocation\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"public_url\x18\x02 \x01(\tR\tpublicUrl\x12\x19\n" +
	"\bnew_vids\x18\x03 \x03(\rR\anewVids\x12!\n" +
	"\fdeleted_vids\x18\x04 \x03(\rR\vdeletedVids\x12\x16\n" +
	"\x06leader\x18\x05 \x01(\tR\x06leader\x12\x1f\n" +
	"\vdata_center\x18\x06 \x01(\tR\n" +
	"dataCenter\x12\x12\n" +
	"\x04rack\x18\a \x01(\tR\x04rack\"\xa1\x02\n" +
	"\rAssignRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x04R\x05count\x12 \n" +
	"\vreplication\x18\x02 \x01(\tR\vreplication\x12\x1e\n" +
	"\n" +
	"collection\x18\x03 \x01(\tR\n" +
	"collection\x12\x10\n" +
	"\x03ttl\x18\x04 \x01(\tR\x03ttl\x12\x1f\n" +
	"\vdata_center\x18\x05 \x01(\tR\n" +
	"dataCenter\x12\x12\n" +
	"\x04rack\x18\x06 \x01(\tR\x04rack\x12\x1b\n" +
	"\tdisk_type\x18\a \x01(\tR\bdiskType\x12 \n" +
	"\vpreallocate\x18\b \x01(\x03R\vpreallocate\x122\n" +
	"\x15writable_volume_count\x18\t \x01(\tR\x13writableVolumeCount\"\x93\x01\n" +
	"\x0eAssignResponse\x12\x10\n" +
	"\x03fid\x18\x01 \x01(\tR\x03fid\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"public_url\x18\x03 \x01(\tR\tpublicUrl\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x04R\x05count\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x12\n" +
	"\x04auth\x18\x06 \x01(\tR\x04auth\"b\n" +
	"\x13LookupVolumeRequest\x12+\n" +
	"\x12volume_or_file_ids\x18\x01 \x03(\tR\x0fvolumeOrFileIds\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\"\xcd\x01\n" +
	"\x14LookupVolumeResponse\x12V\n" +
	"\rlocations_map\x18\x01 \x03(\v21.master_pb.LookupVolumeResponse.LocationsMapEntryR\flocationsMap\x1a]\n" +
	"\x11LocationsMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.master_pb.VolumeIdLocationsR\x05value:\x028\x01\"\\\n" +
	"\x11VolumeIdLocations\x121\n" +
	"\tlocations\x18\x01 \x03(\v2\x13.master_pb.LocationR\tlocations\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\\\n" +
	"\bLocation\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"public_url\x18\x02 \x01(\tR\tpublicUrl\x12\x1f\n" +
	"\vdata_center\x18\x03 \x01(\tR\n" +
	"dataCenter\"\x1f\n" +
	"\x1dGetMasterConfigurationRequest\"\xbe\x01\n" +
	"\x1eGetMasterConfigurationResponse\x12'\n" +
	"\x0fmetrics_address\x18\x01 \x01(\tR\x0emetricsAddress\x12\x16\n" +
	"\x06leader\x18\x02 \x01(\tR\x06leader\x12*\n" +
	"\x11volume_size_limit\x18\x03 \x01(\x04R\x0fvolumeSizeLimit\x12/\n" +
	"\x13default_replication\x18\x04 \x01(\tR\x12defaultReplication\"\x13\n" +
	"\x11VolumeListRequest\"~\n" +
	"\x12VolumeListResponse\x12<\n" +
	"\rtopology_info\x18\x01 \x01(\v2\x17.master_pb.TopologyInfoR\ftopologyInfo\x12*\n" +
	"\x11volume_size_limit\x18\x02 \x01(\x04R\x0fvolumeSizeLimit\"e\n" +
	"\fTopologyInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12E\n" +
	"\x11data_center_infos\x18\x02 \x03(\v2\x19.master_pb.DataCenterInfoR\x0fdataCenterInfos\"T\n" +
	"\x0eDataCenterInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\n" +
	"rack_infos\x18\x02 \x03(\v2\x13.master_pb.RackInfoR\trackInfos\"[\n" +
	"\bRackInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12?\n" +
	"\x0fdata_node_infos\x18\x02 \x03(\v2\x17.master_pb.DataNodeInfoR\rdataNodeInfos\"\xfd\x01\n" +
	"\fDataNodeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"public_url\x18\x02 \x01(\tR\tpublicUrl\x12*\n" +
	"\x11free_volume_count\x18\x03 \x01(\x04R\x0ffreeVolumeCount\x12.\n" +
	"\x13active_volume_count\x18\x04 \x01(\x04R\x11activeVolumeCount\x12.\n" +
	"\x13remote_volume_count\x18\x05 \x01(\x04R\x11remoteVolumeCount\x122\n" +
	"\n" +
	"disk_infos\x18\x06 \x03(\v2\x13.master_pb.DiskInfoR\tdiskInfos\"\xbc\x01\n" +
	"\bDiskInfo\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12F\n" +
	"\fvolume_infos\x18\x02 \x03(\v2#.master_pb.VolumeInformationMessageR\vvolumeInfos\x12(\n" +
	"\x10max_volume_count\x18\x03 \x01(\x04R\x0emaxVolumeCount\x12*\n" +
	"\x11free_volume_count\x18\x04 \x01(\x04R\x0ffreeVolumeCount2\x86\x04\n" +
	"\rMasterService\x12I\n" +
	"\rSendHeartbeat\x12\x14.master_pb.Heartbeat\x1a\x1c.master_pb.HeartbeatResponse\"\x00(\x010\x01\x12X\n" +
	"\rKeepConnected\x12\x1f.master_pb.KeepConnectedRequest\x1a .master_pb.KeepConnectedResponse\"\x00(\x010\x01\x12?\n" +
	"\x06Assign\x12\x18.master_pb.AssignRequest\x1a\x19.master_pb.AssignResponse\"\x00\x12Q\n" +
	"\fLookupVolume\x12\x1e.master_pb.LookupVolumeRequest\x1a\x1f.master_pb.LookupVolumeResponse\"\x00\x12o\n" +
	"\x16GetMasterConfiguration\x12(.master_pb.GetMasterConfigurationRequest\x1a).master_pb.GetMasterConfigurationResponse\"\x00\x12K\n" +
	"\n" +
	"VolumeList\x12\x1c.master_pb.VolumeListRequest\x1a\x1d.master_pb.VolumeListResponse\"\x00B\x15Z\x13goblob/pb/master_pbb\x06proto3"

var (
	file_master_proto_rawDescOnce sync.Once
	file_master_proto_rawDescData []byte
)

func file_master_proto_rawDescGZIP() []byte {
	file_master_proto_rawDescOnce.Do(func() {
		file_master_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_master_proto_rawDesc), len(file_master_proto_rawDesc)))
	})
	return file_master_proto_rawDescData
}

var file_master_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_master_proto_goTypes = []any{
	(*Heartbeat)(nil),                      // 0: master_pb.Heartbeat
	(*MaxVolumeCounts)(nil),                // 1: master_pb.MaxVolumeCounts
	(*HeartbeatResponse)(nil),              // 2: master_pb.HeartbeatResponse
	(*VolumeInformationMessage)(nil),       // 3: master_pb.VolumeInformationMessage
	(*KeepConnectedRequest)(nil),           // 4: master_pb.KeepConnectedRequest
	(*KeepConnectedResponse)(nil),          // 5: master_pb.KeepConnectedResponse
	(*VolumeLocation)(nil),                 // 6: master_pb.VolumeLocation
	(*AssignRequest)(nil),                  // 7: master_pb.AssignRequest
	(*AssignResponse)(nil),                 // 8: master_pb.AssignResponse
	(*LookupVolumeRequest)(nil),            // 9: master_pb.LookupVolumeRequest
	(*LookupVolumeResponse)(nil),           // 10: master_pb.LookupVolumeResponse
	(*VolumeIdLocations)(nil),              // 11: master_pb.VolumeIdLocations
	(*Location)(nil),                       // 12: master_pb.Location
	(*GetMasterConfigurationRequest)(nil),  // 13: master_pb.GetMasterConfigurationRequest
	(*GetMasterConfigurationResponse)(nil), // 14: master_pb.GetMasterConfigurationResponse
	(*VolumeListRequest)(nil),              // 15: master_pb.VolumeListRequest
	(*VolumeListResponse)(nil),             // 16: master_pb.VolumeListResponse
	(*TopologyInfo)(nil),                   // 17: master_pb.TopologyInfo
	(*DataCenterInfo)(nil),                 // 18: master_pb.DataCenterInfo
	(*RackInfo)(nil),                       // 19: master_pb.RackInfo
	(*DataNodeInfo)(nil),                   // 20: master_pb.DataNodeInfo
	(*DiskInfo)(nil),                       // 21: master_pb.DiskInfo
	nil,                                    // 22: master_pb.LookupVolumeResponse.LocationsMapEntry
}
var file_master_proto_depIdxs = []int32{
	3,  // 0: master_pb.Heartbeat.volumes:type_name -> master_pb.VolumeInformationMessage
	1,  // 1: master_pb.Heartbeat.max_volume_counts:type_name -> master_pb.MaxVolumeCounts
	6,  // 2: master_pb.KeepConnectedResponse.volume_locations:type_name -> master_pb.VolumeLocation
	22, // 3: master_pb.LookupVolumeResponse.locations_map:type_name -> master_pb.LookupVolumeResponse.LocationsMapEntry
	12, // 4: master_pb.VolumeIdLocations.locations:type_name -> master_pb.Location
	17, // 5: master_pb.VolumeListResponse.topology_info:type_name -> master_pb.TopologyInfo
	18, // 6: master_pb.TopologyInfo.data_center_infos:type_name -> master_pb.DataCenterInfo
	19, // 7: master_pb.DataCenterInfo.rack_infos:type_name -> master_pb.RackInfo
	20, // 8: master_pb.RackInfo.data_node_infos:type_name -> master_pb.DataNodeInfo
	21, // 9: master_pb.DataNodeInfo.disk_infos:type_name -> master_pb.DiskInfo
	3,  // 10: master_pb.DiskInfo.volume_infos:type_name -> master_pb.VolumeInformationMessage
	11, // 11: master_pb.LookupVolumeResponse.LocationsMapEntry.value:type_name -> master_pb.VolumeIdLocations
	0,  // 12: master_pb.MasterService.SendHeartbeat:input_type -> master_pb.Heartbeat
	4,  // 13: master_pb.MasterService.KeepConnected:input_type -> master_pb.KeepConnectedRequest
	7,  // 14: master_pb.MasterService.Assign:input_type -> master_pb.AssignRequest
	9,  // 15: master_pb.MasterService.LookupVolume:input_type -> master_pb.LookupVolumeRequest
	13, // 16: master_pb.MasterService.GetMasterConfiguration:input_type -> master_pb.GetMasterConfigurationRequest
	15, // 17: master_pb.MasterService.VolumeList:input_type -> master_pb.VolumeListRequest
	2,  // 18: master_pb.MasterService.SendHeartbeat:output_type -> master_pb.HeartbeatResponse
	5,  // 19: master_pb.MasterService.KeepConnected:output_type -> master_pb.KeepConnectedResponse
	8,  // 20: master_pb.MasterService.Assign:output_type -> master_pb.AssignResponse
	10, // 21: master_pb.MasterService.LookupVolume:output_type -> master_pb.LookupVolumeResponse
	14, // 22: master_pb.MasterService.GetMasterConfiguration:output_type -> master_pb.GetMasterConfigurationResponse
	16, // 23: master_pb.MasterService.VolumeList:output_type -> master_pb.VolumeListResponse
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_master_proto_init() }
func file_master_proto_init() {
	if File_master_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_master_proto_rawDesc), len(file_master_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_master_proto_goTypes,
		DependencyIndexes: file_master_proto_depIdxs,
		MessageInfos:      file_master_proto_msgTypes,
	}.Build()
	File_master_proto = out.File
	file_master_proto_goTypes = nil
	file_master_proto_depIdxs = nil
}
