// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: filer.proto

package filer_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Entry is the core filer metadata type representing a file or directory.
type Entry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDirectory     bool                   `protobuf:"varint,2,opt,name=is_directory,json=isDirectory,proto3" json:"is_directory,omitempty"`
	Chunks          []*FileChunk           `protobuf:"bytes,3,rep,name=chunks,proto3" json:"chunks,omitempty"`
	Attributes      *FuseAttributes        `protobuf:"bytes,4,opt,name=attributes,proto3" json:"attributes,omitempty"`
	Extended        map[string][]byte      `protobuf:"bytes,5,rep,name=extended,proto3" json:"extended,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Content         []byte                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	HardLinkId      []byte                 `protobuf:"bytes,7,opt,name=hard_link_id,json=hardLinkId,proto3" json:"hard_link_id,omitempty"`
	HardLinkCounter int32                  `protobuf:"varint,8,opt,name=hard_link_counter,json=hardLinkCounter,proto3" json:"hard_link_counter,omitempty"`
	Remote          *RemoteEntry           `protobuf:"bytes,9,opt,name=remote,proto3" json:"remote,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_filer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Entry) GetIsDirectory() bool {
	if x != nil {
		return x.IsDirectory
	}
	return false
}

func (x *Entry) GetChunks() []*FileChunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *Entry) GetAttributes() *FuseAttributes {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Entry) GetExtended() map[string][]byte {
	if x != nil {
		return x.Extended
	}
	return nil
}

func (x *Entry) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Entry) GetHardLinkId() []byte {
	if x != nil {
		return x.HardLinkId
	}
	return nil
}

func (x *Entry) GetHardLinkCounter() int32 {
	if x != nil {
		return x.HardLinkCounter
	}
	return 0
}

func (x *Entry) GetRemote() *RemoteEntry {
	if x != nil {
		return x.Remote
	}
	return nil
}

type FileChunk struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FileId          string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Offset          int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Size            uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	ModifiedTsNs    int64                  `protobuf:"varint,4,opt,name=modified_ts_ns,json=modifiedTsNs,proto3" json:"modified_ts_ns,omitempty"`
	ETag            string                 `protobuf:"bytes,5,opt,name=e_tag,json=eTag,proto3" json:"e_tag,omitempty"`
	CipherKey       []byte                 `protobuf:"bytes,6,opt,name=cipher_key,json=cipherKey,proto3" json:"cipher_key,omitempty"`
	IsCompressed    bool                   `protobuf:"varint,7,opt,name=is_compressed,json=isCompressed,proto3" json:"is_compressed,omitempty"`
	IsChunkManifest bool                   `protobuf:"varint,8,opt,name=is_chunk_manifest,json=isChunkManifest,proto3" json:"is_chunk_manifest,omitempty"`
	Fid             string                 `protobuf:"bytes,9,opt,name=fid,proto3" json:"fid,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_filer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{1}
}

func (x *FileChunk) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FileChunk) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileChunk) GetModifiedTsNs() int64 {
	if x != nil {
		return x.ModifiedTsNs
	}
	return 0
}

func (x *FileChunk) GetETag() string {
	if x != nil {
		return x.ETag
	}
	return ""
}

func (x *FileChunk) GetCipherKey() []byte {
	if x != nil {
		return x.CipherKey
	}
	return nil
}

func (x *FileChunk) GetIsCompressed() bool {
	if x != nil {
		return x.IsCompressed
	}
	return false
}

func (x *FileChunk) GetIsChunkManifest() bool {
	if x != nil {
		return x.IsChunkManifest
	}
	return false
}

func (x *FileChunk) GetFid() string {
	if x != nil {
		return x.Fid
	}
	return ""
}

type FuseAttributes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileSize      uint64                 `protobuf:"varint,1,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Mtime         int64                  `protobuf:"varint,2,opt,name=mtime,proto3" json:"mtime,omitempty"`
	FileMode      uint32                 `protobuf:"varint,3,opt,name=file_mode,json=fileMode,proto3" json:"file_mode,omitempty"`
	Uid           uint32                 `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           uint32                 `protobuf:"varint,5,opt,name=gid,proto3" json:"gid,omitempty"`
	Crtime        int64                  `protobuf:"varint,6,opt,name=crtime,proto3" json:"crtime,omitempty"`
	Mime          string                 `protobuf:"bytes,7,opt,name=mime,proto3" json:"mime,omitempty"`
	Replication   string                 `protobuf:"bytes,8,opt,name=replication,proto3" json:"replication,omitempty"`
	Collection    string                 `protobuf:"bytes,9,opt,name=collection,proto3" json:"collection,omitempty"`
	TtlSec        int32                  `protobuf:"varint,10,opt,name=ttl_sec,json=ttlSec,proto3" json:"ttl_sec,omitempty"`
	UserName      string                 `protobuf:"bytes,11,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	GroupNames    []string               `protobuf:"bytes,12,rep,name=group_names,json=groupNames,proto3" json:"group_names,omitempty"`
	SymlinkTarget string                 `protobuf:"bytes,13,opt,name=symlink_target,json=symlinkTarget,proto3" json:"symlink_target,omitempty"`
	Md5           string                 `protobuf:"bytes,14,opt,name=md5,proto3" json:"md5,omitempty"`
	DiskType      string                 `protobuf:"bytes,15,opt,name=disk_type,json=diskType,proto3" json:"disk_type,omitempty"`
	IsRemote      bool                   `protobuf:"varint,16,opt,name=is_remote,json=isRemote,proto3" json:"is_remote,omitempty"`
	Inode         uint64                 `protobuf:"varint,17,opt,name=inode,proto3" json:"inode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FuseAttributes) Reset() {
	*x = FuseAttributes{}
	mi := &file_filer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FuseAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuseAttributes) ProtoMessage() {}

func (x *FuseAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuseAttributes.ProtoReflect.Descriptor instead.
func (*FuseAttributes) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{2}
}

func (x *FuseAttributes) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *FuseAttributes) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

func (x *FuseAttributes) GetFileMode() uint32 {
	if x != nil {
		return x.FileMode
	}
	return 0
}

func (x *FuseAttributes) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *FuseAttributes) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *FuseAttributes) GetCrtime() int64 {
	if x != nil {
		return x.Crtime
	}
	return 0
}

func (x *FuseAttributes) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *FuseAttributes) GetReplication() string {
	if x != nil {
		return x.Replication
	}
	return ""
}

func (x *FuseAttributes) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *FuseAttributes) GetTtlSec() int32 {
	if x != nil {
		return x.TtlSec
	}
	return 0
}

func (x *FuseAttributes) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *FuseAttributes) GetGroupNames() []string {
	if x != nil {
		return x.GroupNames
	}
	return nil
}

func (x *FuseAttributes) GetSymlinkTarget() string {
	if x != nil {
		return x.SymlinkTarget
	}
	return ""
}

func (x *FuseAttributes) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *FuseAttributes) GetDiskType() string {
	if x != nil {
		return x.DiskType
	}
	return ""
}

func (x *FuseAttributes) GetIsRemote() bool {
	if x != nil {
		return x.IsRemote
	}
	return false
}

func (x *FuseAttributes) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

type RemoteEntry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	StorageName       string                 `protobuf:"bytes,1,opt,name=storage_name,json=storageName,proto3" json:"storage_name,omitempty"`
	RemotePath        string                 `protobuf:"bytes,2,opt,name=remote_path,json=remotePath,proto3" json:"remote_path,omitempty"`
	RemoteSize        int64                  `protobuf:"varint,3,opt,name=remote_size,json=remoteSize,proto3" json:"remote_size,omitempty"`
	RemoteETag        string                 `protobuf:"bytes,4,opt,name=remote_e_tag,json=remoteETag,proto3" json:"remote_e_tag,omitempty"`
	LastLocalSyncTsNs int64                  `protobuf:"varint,5,opt,name=last_local_sync_ts_ns,json=lastLocalSyncTsNs,proto3" json:"last_local_sync_ts_ns,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RemoteEntry) Reset() {
	*x = RemoteEntry{}
	mi := &file_filer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteEntry) ProtoMessage() {}

func (x *RemoteEntry) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteEntry.ProtoReflect.Descriptor instead.
func (*RemoteEntry) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{3}
}

func (x *RemoteEntry) GetStorageName() string {
	if x != nil {
		return x.StorageName
	}
	return ""
}

func (x *RemoteEntry) GetRemotePath() string {
	if x != nil {
		return x.RemotePath
	}
	return ""
}

func (x *RemoteEntry) GetRemoteSize() int64 {
	if x != nil {
		return x.RemoteSize
	}
	return 0
}

func (x *RemoteEntry) GetRemoteETag() string {
	if x != nil {
		return x.RemoteETag
	}
	return ""
}

func (x *RemoteEntry) GetLastLocalSyncTsNs() int64 {
	if x != nil {
		return x.LastLocalSyncTsNs
	}
	return 0
}

type LookupDirectoryEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Directory     string                 `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupDirectoryEntryRequest) Reset() {
	*x = LookupDirectoryEntryRequest{}
	mi := &file_filer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupDirectoryEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupDirectoryEntryRequest) ProtoMessage() {}

func (x *LookupDirectoryEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupDirectoryEntryRequest.ProtoReflect.Descriptor instead.
func (*LookupDirectoryEntryRequest) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{4}
}

func (x *LookupDirectoryEntryRequest) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

func (x *LookupDirectoryEntryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LookupDirectoryEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *Entry                 `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupDirectoryEntryResponse) Reset() {
	*x = LookupDirectoryEntryResponse{}
	mi := &file_filer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupDirectoryEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupDirectoryEntryResponse) ProtoMessage() {}

func (x *LookupDirectoryEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupDirectoryEntryResponse.ProtoReflect.Descriptor instead.
func (*LookupDirectoryEntryResponse) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{5}
}

func (x *LookupDirectoryEntryResponse) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *LookupDirectoryEntryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListEntriesRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Directory          string                 `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`
	Prefix             string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	StartFromFileName  string                 `protobuf:"bytes,3,opt,name=start_from_file_name,json=startFromFileName,proto3" json:"start_from_file_name,omitempty"`
	InclusiveStartFrom bool                   `protobuf:"varint,4,opt,name=inclusive_start_from,json=inclusiveStartFrom,proto3" json:"inclusive_start_from,omitempty"`
	Limit              uint32                 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListEntriesRequest) Reset() {
	*x = ListEntriesRequest{}
	mi := &file_filer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesRequest) ProtoMessage() {}

func (x *ListEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesRequest.ProtoReflect.Descriptor instead.
func (*ListEntriesRequest) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{6}
}

func (x *ListEntriesRequest) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

func (x *ListEntriesRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ListEntriesRequest) GetStartFromFileName() string {
	if x != nil {
		return x.StartFromFileName
	}
	return ""
}

func (x *ListEntriesRequest) GetInclusiveStartFrom() bool {
	if x != nil {
		return x.InclusiveStartFrom
	}
	return false
}

func (x *ListEntriesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *Entry                 `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntriesResponse) Reset() {
	*x = ListEntriesResponse{}
	mi := &file_filer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesResponse) ProtoMessage() {}

func (x *ListEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesResponse.ProtoReflect.Descriptor instead.
func (*ListEntriesResponse) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{7}
}

func (x *ListEntriesResponse) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type CreateEntryRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Directory          string                 `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`
	Entry              *Entry                 `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	OExcl              bool                   `protobuf:"varint,3,opt,name=o_excl,json=oExcl,proto3" json:"o_excl,omitempty"`
	IsFromOtherCluster bool                   `protobuf:"varint,4,opt,name=is_from_other_cluster,json=isFromOtherCluster,proto3" json:"is_from_other_cluster,omitempty"`
	Signatures         []string               `protobuf:"bytes,5,rep,name=signatures,proto3" json:"signatures,omitempty"`
	SkipCheckParentDir bool                   `protobuf:"varint,6,opt,name=skip_check_parent_dir,json=skipCheckParentDir,proto3" json:"skip_check_parent_dir,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateEntryRequest) Reset() {
	*x = CreateEntryRequest{}
	mi := &file_filer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEntryRequest) ProtoMessage() {}

func (x *CreateEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEntryRequest.ProtoReflect.Descriptor instead.
func (*CreateEntryRequest) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{8}
}

func (x *CreateEntryRequest) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

func (x *CreateEntryRequest) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *CreateEntryRequest) GetOExcl() bool {
	if x != nil {
		return x.OExcl
	}
	return false
}

func (x *CreateEntryRequest) GetIsFromOtherCluster() bool {
	if x != nil {
		return x.IsFromOtherCluster
	}
	return false
}

func (x *CreateEntryRequest) GetSignatures() []string {
	if x != nil {
		return x.Signatures
	}
	return nil
}

func (x *CreateEntryRequest) GetSkipCheckParentDir() bool {
	if x != nil {
		return x.SkipCheckParentDir
	}
	return false
}

type CreateEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEntryResponse) Reset() {
	*x = CreateEntryResponse{}
	mi := &file_filer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEntryResponse) ProtoMessage() {}

func (x *CreateEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEntryResponse.ProtoReflect.Descriptor instead.
func (*CreateEntryResponse) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{9}
}

func (x *CreateEntryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateEntryRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Directory          string                 `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`
	Entry              *Entry                 `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	IsFromOtherCluster bool                   `protobuf:"varint,3,opt,name=is_from_other_cluster,json=isFromOtherCluster,proto3" json:"is_from_other_cluster,omitempty"`
	Signatures         []string               `protobuf:"bytes,4,rep,name=signatures,proto3" json:"signatures,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateEntryRequest) Reset() {
	*x = UpdateEntryRequest{}
	mi := &file_filer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEntryRequest) ProtoMessage() {}

func (x *UpdateEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEntryRequest.ProtoReflect.Descriptor instead.
func (*UpdateEntryRequest) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateEntryRequest) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

func (x *UpdateEntryRequest) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *UpdateEntryRequest) GetIsFromOtherCluster() bool {
	if x != nil {
		return x.IsFromOtherCluster
	}
	return false
}

func (x *UpdateEntryRequest) GetSignatures() []string {
	if x != nil {
		return x.Signatures
	}
	return nil
}

type UpdateEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEntryResponse) Reset() {
	*x = UpdateEntryResponse{}
	mi := &file_filer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEntryResponse) ProtoMessage() {}

func (x *UpdateEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEntryResponse.ProtoReflect.Descriptor instead.
func (*UpdateEntryResponse) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateEntryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AppendToEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Directory     string                 `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`
	EntryName     string                 `protobuf:"bytes,2,opt,name=entry_name,json=entryName,proto3" json:"entry_name,omitempty"`
	Chunks        []*FileChunk           `protobuf:"bytes,3,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendToEntryRequest) Reset() {
	*x = AppendToEntryRequest{}
	mi := &file_filer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendToEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendToEntryRequest) ProtoMessage() {}

func (x *AppendToEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendToEntryRequest.ProtoReflect.Descriptor instead.
func (*AppendToEntryRequest) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{12}
}

func (x *AppendToEntryRequest) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

func (x *AppendToEntryRequest) GetEntryName() string {
	if x != nil {
		return x.EntryName
	}
	return ""
}

func (x *AppendToEntryRequest) GetChunks() []*FileChunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type AppendToEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendToEntryResponse) Reset() {
	*x = AppendToEntryResponse{}
	mi := &file_filer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendToEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendToEntryResponse) ProtoMessage() {}

func (x *AppendToEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendToEntryResponse.ProtoReflect.Descriptor instead.
func (*AppendToEntryResponse) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{13}
}

func (x *AppendToEntryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteEntryRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Directory            string                 `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsDeleteData         bool                   `protobuf:"varint,3,opt,name=is_delete_data,json=isDeleteData,proto3" json:"is_delete_data,omitempty"`
	IsRecursive          bool                   `protobuf:"varint,4,opt,name=is_recursive,json=isRecursive,proto3" json:"is_recursive,omitempty"`
	IgnoreRecursiveError bool                   `protobuf:"varint,5,opt,name=ignore_recursive_error,json=ignoreRecursiveError,proto3" json:"ignore_recursive_error,omitempty"`
	IsFromOtherCluster   bool                   `protobuf:"varint,6,opt,name=is_from_other_cluster,json=isFromOtherCluster,proto3" json:"is_from_other_cluster,omitempty"`
	Signatures           []string               `protobuf:"bytes,7,rep,name=signatures,proto3" json:"signatures,omitempty"`
	Chunks               []*FileChunk           `protobuf:"bytes,8,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DeleteEntryRequest) Reset() {
	*x = DeleteEntryRequest{}
	mi := &file_filer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEntryRequest) ProtoMessage() {}

func (x *DeleteEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEntryRequest.ProtoReflect.Descriptor instead.
func (*DeleteEntryRequest) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteEntryRequest) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

func (x *DeleteEntryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteEntryRequest) GetIsDeleteData() bool {
	if x != nil {
		return x.IsDeleteData
	}
	return false
}

func (x *DeleteEntryRequest) GetIsRecursive() bool {
	if x != nil {
		return x.IsRecursive
	}
	return false
}

func (x *DeleteEntryRequest) GetIgnoreRecursiveError() bool {
	if x != nil {
		return x.IgnoreRecursiveError
	}
	return false
}

func (x *DeleteEntryRequest) GetIsFromOtherCluster() bool {
	if x != nil {
		return x.IsFromOtherCluster
	}
	return false
}

func (x *DeleteEntryRequest) GetSignatures() []string {
	if x != nil {
		return x.Signatures
	}
	return nil
}

func (x *DeleteEntryRequest) GetChunks() []*FileChunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type DeleteEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEntryResponse) Reset() {
	*x = DeleteEntryResponse{}
	mi := &file_filer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEntryResponse) ProtoMessage() {}

func (x *DeleteEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEntryResponse.ProtoReflect.Descriptor instead.
func (*DeleteEntryResponse) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteEntryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AtomicRenameEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldDirectory  string                 `protobuf:"bytes,1,opt,name=old_directory,json=oldDirectory,proto3" json:"old_directory,omitempty"`
	OldName       string                 `protobuf:"bytes,2,opt,name=old_name,json=oldName,proto3" json:"old_name,omitempty"`
	NewDirectory  string                 `protobuf:"bytes,3,opt,name=new_directory,json=newDirectory,proto3" json:"new_directory,omitempty"`
	NewName       string                 `protobuf:"bytes,4,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AtomicRenameEntryRequest) Reset() {
	*x = AtomicRenameEntryRequest{}
	mi := &file_filer_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtomicRenameEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtomicRenameEntryRequest) ProtoMessage() {}

func (x *AtomicRenameEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtomicRenameEntryRequest.ProtoReflect.Descriptor instead.
func (*AtomicRenameEntryRequest) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{16}
}

func (x *AtomicRenameEntryRequest) GetOldDirectory() string {
	if x != nil {
		return x.OldDirectory
	}
	return ""
}

func (x *AtomicRenameEntryRequest) GetOldName() string {
	if x != nil {
		return x.OldName
	}
	return ""
}

func (x *AtomicRenameEntryRequest) GetNewDirectory() string {
	if x != nil {
		return x.NewDirectory
	}
	return ""
}

func (x *AtomicRenameEntryRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type AtomicRenameEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AtomicRenameEntryResponse) Reset() {
	*x = AtomicRenameEntryResponse{}
	mi := &file_filer_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtomicRenameEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtomicRenameEntryResponse) ProtoMessage() {}

func (x *AtomicRenameEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtomicRenameEntryResponse.ProtoReflect.Descriptor instead.
func (*AtomicRenameEntryResponse) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{17}
}

func (x *AtomicRenameEntryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StreamRenameEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldDirectory  string                 `protobuf:"bytes,1,opt,name=old_directory,json=oldDirectory,proto3" json:"old_directory,omitempty"`
	OldName       string                 `protobuf:"bytes,2,opt,name=old_name,json=oldName,proto3" json:"old_name,omitempty"`
	NewDirectory  string                 `protobuf:"bytes,3,opt,name=new_directory,json=newDirectory,proto3" json:"new_directory,omitempty"`
	NewName       string                 `protobuf:"bytes,4,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	Signatures    []string               `protobuf:"bytes,5,rep,name=signatures,proto3" json:"signatures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRenameEntryRequest) Reset() {
	*x = StreamRenameEntryRequest{}
	mi := &file_filer_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRenameEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRenameEntryRequest) ProtoMessage() {}

func (x *StreamRenameEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRenameEntryRequest.ProtoReflect.Descriptor instead.
func (*StreamRenameEntryRequest) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{18}
}

func (x *StreamRenameEntryRequest) GetOldDirectory() string {
	if x != nil {
		return x.OldDirectory
	}
	return ""
}

func (x *StreamRenameEntryRequest) GetOldName() string {
	if x != nil {
		return x.OldName
	}
	return ""
}

func (x *StreamRenameEntryRequest) GetNewDirectory() string {
	if x != nil {
		return x.NewDirectory
	}
	return ""
}

func (x *StreamRenameEntryRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

func (x *StreamRenameEntryRequest) GetSignatures() []string {
	if x != nil {
		return x.Signatures
	}
	return nil
}

type StreamRenameEntryResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Entry             *Entry                 `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	EventNotification string                 `protobuf:"bytes,2,opt,name=event_notification,json=eventNotification,proto3" json:"event_notification,omitempty"`
	NewParentPath     string                 `protobuf:"bytes,3,opt,name=new_parent_path,json=newParentPath,proto3" json:"new_parent_path,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StreamRenameEntryResponse) Reset() {
	*x = StreamRenameEntryResponse{}
	mi := &file_filer_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRenameEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRenameEntryResponse) ProtoMessage() {}

func (x *StreamRenameEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRenameEntryResponse.ProtoReflect.Descriptor instead.
func (*StreamRenameEntryResponse) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{19}
}

func (x *StreamRenameEntryResponse) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *StreamRenameEntryResponse) GetEventNotification() string {
	if x != nil {
		return x.EventNotification
	}
	return ""
}

func (x *StreamRenameEntryResponse) GetNewParentPath() string {
	if x != nil {
		return x.NewParentPath
	}
	return ""
}

type AssignVolumeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Count            uint32                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Collection       string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Replication      string                 `protobuf:"bytes,3,opt,name=replication,proto3" json:"replication,omitempty"`
	Ttl              string                 `protobuf:"bytes,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	DiskType         string                 `protobuf:"bytes,5,opt,name=disk_type,json=diskType,proto3" json:"disk_type,omitempty"`
	DataCenter       string                 `protobuf:"bytes,6,opt,name=data_center,json=dataCenter,proto3" json:"data_center,omitempty"`
	Rack             string                 `protobuf:"bytes,7,opt,name=rack,proto3" json:"rack,omitempty"`
	ReplicationAsMin int32                  `protobuf:"varint,8,opt,name=replication_as_min,json=replicationAsMin,proto3" json:"replication_as_min,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AssignVolumeRequest) Reset() {
	*x = AssignVolumeRequest{}
	mi := &file_filer_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignVolumeRequest) ProtoMessage() {}

func (x *AssignVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignVolumeRequest.ProtoReflect.Descriptor instead.
func (*AssignVolumeRequest) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{20}
}

func (x *AssignVolumeRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AssignVolumeRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *AssignVolumeRequest) GetReplication() string {
	if x != nil {
		return x.Replication
	}
	return ""
}

func (x *AssignVolumeRequest) GetTtl() string {
	if x != nil {
		return x.Ttl
	}
	return ""
}

func (x *AssignVolumeRequest) GetDiskType() string {
	if x != nil {
		return x.DiskType
	}
	return ""
}

func (x *AssignVolumeRequest) GetDataCenter() string {
	if x != nil {
		return x.DataCenter
	}
	return ""
}

func (x *AssignVolumeRequest) GetRack() string {
	if x != nil {
		return x.Rack
	}
	return ""
}

func (x *AssignVolumeRequest) GetReplicationAsMin() int32 {
	if x != nil {
		return x.ReplicationAsMin
	}
	return 0
}

type AssignVolumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	PublicUrl     string                 `protobuf:"bytes,3,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Auth          string                 `protobuf:"bytes,5,opt,name=auth,proto3" json:"auth,omitempty"`
	Collection    string                 `protobuf:"bytes,6,opt,name=collection,proto3" json:"collection,omitempty"`
	Replication   string                 `protobuf:"bytes,7,opt,name=replication,proto3" json:"replication,omitempty"`
	Ttl           string                 `protobuf:"bytes,8,opt,name=ttl,proto3" json:"ttl,omitempty"`
	DiskType      string                 `protobuf:"bytes,9,opt,name=disk_type,json=diskType,proto3" json:"disk_type,omitempty"`
	Error         string                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignVolumeResponse) Reset() {
	*x = AssignVolumeResponse{}
	mi := &file_filer_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignVolumeResponse) ProtoMessage() {}

func (x *AssignVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignVolumeResponse.ProtoReflect.Descriptor instead.
func (*AssignVolumeResponse) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{21}
}

func (x *AssignVolumeResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *AssignVolumeResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AssignVolumeResponse) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

func (x *AssignVolumeResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AssignVolumeResponse) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

func (x *AssignVolumeResponse) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *AssignVolumeResponse) GetReplication() string {
	if x != nil {
		return x.Replication
	}
	return ""
}

func (x *AssignVolumeResponse) GetTtl() string {
	if x != nil {
		return x.Ttl
	}
	return ""
}

func (x *AssignVolumeResponse) GetDiskType() string {
	if x != nil {
		return x.DiskType
	}
	return ""
}

func (x *AssignVolumeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LookupVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeIds     []string               `protobuf:"bytes,1,rep,name=volume_ids,json=volumeIds,proto3" json:"volume_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupVolumeRequest) Reset() {
	*x = LookupVolumeRequest{}
	mi := &file_filer_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupVolumeRequest) ProtoMessage() {}

func (x *LookupVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupVolumeRequest.ProtoReflect.Descriptor instead.
func (*LookupVolumeRequest) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{22}
}

func (x *LookupVolumeRequest) GetVolumeIds() []string {
	if x != nil {
		return x.VolumeIds
	}
	return nil
}

type LookupVolumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationsMap  map[string]*Locations  `protobuf:"bytes,1,rep,name=locations_map,json=locationsMap,proto3" json:"locations_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupVolumeResponse) Reset() {
	*x = LookupVolumeResponse{}
	mi := &file_filer_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupVolumeResponse) ProtoMessage() {}

func (x *LookupVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupVolumeResponse.ProtoReflect.Descriptor instead.
func (*LookupVolumeResponse) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{23}
}

func (x *LookupVolumeResponse) GetLocationsMap() map[string]*Locations {
	if x != nil {
		return x.LocationsMap
	}
	return nil
}

type Locations struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locations     []*Location            `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Locations) Reset() {
	*x = Locations{}
	mi := &file_filer_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Locations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Locations) ProtoMessage() {}

func (x *Locations) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Locations.ProtoReflect.Descriptor instead.
func (*Locations) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{24}
}

func (x *Locations) GetLocations() []*Location {
	if x != nil {
		return x.Locations
	}
	return nil
}

func (x *Locations) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	PublicUrl     string                 `protobuf:"bytes,2,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"`
	DataCenter    string                 `protobuf:"bytes,3,opt,name=data_center,json=dataCenter,proto3" json:"data_center,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_filer_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{25}
}

func (x *Location) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Location) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

func (x *Location) GetDataCenter() string {
	if x != nil {
		return x.DataCenter
	}
	return ""
}

type SubscribeMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PathPrefix    string                 `protobuf:"bytes,1,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"`
	SinceNs       int64                  `protobuf:"varint,2,opt,name=since_ns,json=sinceNs,proto3" json:"since_ns,omitempty"`
	ClientId      int32                  `protobuf:"varint,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientName    string                 `protobuf:"bytes,4,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	WatchedEvents []string               `protobuf:"bytes,5,rep,name=watched_events,json=watchedEvents,proto3" json:"watched_events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeMetadataRequest) Reset() {
	*x = SubscribeMetadataRequest{}
	mi := &file_filer_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeMetadataRequest) ProtoMessage() {}

func (x *SubscribeMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeMetadataRequest.ProtoReflect.Descriptor instead.
func (*SubscribeMetadataRequest) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{26}
}

func (x *SubscribeMetadataRequest) GetPathPrefix() string {
	if x != nil {
		return x.PathPrefix
	}
	return ""
}

func (x *SubscribeMetadataRequest) GetSinceNs() int64 {
	if x != nil {
		return x.SinceNs
	}
	return 0
}

func (x *SubscribeMetadataRequest) GetClientId() int32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *SubscribeMetadataRequest) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *SubscribeMetadataRequest) GetWatchedEvents() []string {
	if x != nil {
		return x.WatchedEvents
	}
	return nil
}

type SubscribeMetadataResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Directory         string                 `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`
	EventNotification *EventNotification     `protobuf:"bytes,2,opt,name=event_notification,json=eventNotification,proto3" json:"event_notification,omitempty"`
	TsNs              int64                  `protobuf:"varint,3,opt,name=ts_ns,json=tsNs,proto3" json:"ts_ns,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SubscribeMetadataResponse) Reset() {
	*x = SubscribeMetadataResponse{}
	mi := &file_filer_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeMetadataResponse) ProtoMessage() {}

func (x *SubscribeMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeMetadataResponse.ProtoReflect.Descriptor instead.
func (*SubscribeMetadataResponse) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{27}
}

func (x *SubscribeMetadataResponse) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

func (x *SubscribeMetadataResponse) GetEventNotification() *EventNotification {
	if x != nil {
		return x.EventNotification
	}
	return nil
}

func (x *SubscribeMetadataResponse) GetTsNs() int64 {
	if x != nil {
		return x.TsNs
	}
	return 0
}

type EventNotification struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	OldEntry           *Entry                 `protobuf:"bytes,1,opt,name=old_entry,json=oldEntry,proto3" json:"old_entry,omitempty"`
	NewEntry           *Entry                 `protobuf:"bytes,2,opt,name=new_entry,json=newEntry,proto3" json:"new_entry,omitempty"`
	DeleteChunks       bool                   `protobuf:"varint,3,opt,name=delete_chunks,json=deleteChunks,proto3" json:"delete_chunks,omitempty"`
	NewParentPath      string                 `protobuf:"bytes,4,opt,name=new_parent_path,json=newParentPath,proto3" json:"new_parent_path,omitempty"`
	IsFromOtherCluster bool                   `protobuf:"varint,5,opt,name=is_from_other_cluster,json=isFromOtherCluster,proto3" json:"is_from_other_cluster,omitempty"`
	Signatures         []string               `protobuf:"bytes,6,rep,name=signatures,proto3" json:"signatures,omitempty"`
	IsTruncate         bool                   `protobuf:"varint,7,opt,name=is_truncate,json=isTruncate,proto3" json:"is_truncate,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EventNotification) Reset() {
	*x = EventNotification{}
	mi := &file_filer_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventNotification) ProtoMessage() {}

func (x *EventNotification) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventNotification.ProtoReflect.Descriptor instead.
func (*EventNotification) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{28}
}

func (x *EventNotification) GetOldEntry() *Entry {
	if x != nil {
		return x.OldEntry
	}
	return nil
}

func (x *EventNotification) GetNewEntry() *Entry {
	if x != nil {
		return x.NewEntry
	}
	return nil
}

func (x *EventNotification) GetDeleteChunks() bool {
	if x != nil {
		return x.DeleteChunks
	}
	return false
}

func (x *EventNotification) GetNewParentPath() string {
	if x != nil {
		return x.NewParentPath
	}
	return ""
}

func (x *EventNotification) GetIsFromOtherCluster() bool {
	if x != nil {
		return x.IsFromOtherCluster
	}
	return false
}

func (x *EventNotification) GetSignatures() []string {
	if x != nil {
		return x.Signatures
	}
	return nil
}

func (x *EventNotification) GetIsTruncate() bool {
	if x != nil {
		return x.IsTruncate
	}
	return false
}

type KvGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvGetRequest) Reset() {
	*x = KvGetRequest{}
	mi := &file_filer_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvGetRequest) ProtoMessage() {}

func (x *KvGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvGetRequest.ProtoReflect.Descriptor instead.
func (*KvGetRequest) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{29}
}

func (x *KvGetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type KvGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvGetResponse) Reset() {
	*x = KvGetResponse{}
	mi := &file_filer_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvGetResponse) ProtoMessage() {}

func (x *KvGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvGetResponse.ProtoReflect.Descriptor instead.
func (*KvGetResponse) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{30}
}

func (x *KvGetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *KvGetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type KvPutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvPutRequest) Reset() {
	*x = KvPutRequest{}
	mi := &file_filer_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvPutRequest) ProtoMessage() {}

func (x *KvPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvPutRequest.ProtoReflect.Descriptor instead.
func (*KvPutRequest) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{31}
}

func (x *KvPutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KvPutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type KvPutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvPutResponse) Reset() {
	*x = KvPutResponse{}
	mi := &file_filer_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvPutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvPutResponse) ProtoMessage() {}

func (x *KvPutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvPutResponse.ProtoReflect.Descriptor instead.
func (*KvPutResponse) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{32}
}

func (x *KvPutResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type KvDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvDeleteRequest) Reset() {
	*x = KvDeleteRequest{}
	mi := &file_filer_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvDeleteRequest) ProtoMessage() {}

func (x *KvDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvDeleteRequest.ProtoReflect.Descriptor instead.
func (*KvDeleteRequest) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{33}
}

func (x *KvDeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type KvDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvDeleteResponse) Reset() {
	*x = KvDeleteResponse{}
	mi := &file_filer_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvDeleteResponse) ProtoMessage() {}

func (x *KvDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvDeleteResponse.ProtoReflect.Descriptor instead.
func (*KvDeleteResponse) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{34}
}

func (x *KvDeleteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetFilerConfigurationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFilerConfigurationRequest) Reset() {
	*x = GetFilerConfigurationRequest{}
	mi := &file_filer_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFilerConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilerConfigurationRequest) ProtoMessage() {}

func (x *GetFilerConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilerConfigurationRequest.ProtoReflect.Descriptor instead.
func (*GetFilerConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{35}
}

type GetFilerConfigurationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Masters        string                 `protobuf:"bytes,1,opt,name=masters,proto3" json:"masters,omitempty"`
	Replication    string                 `protobuf:"bytes,2,opt,name=replication,proto3" json:"replication,omitempty"`
	Collection     string                 `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	MaxMb          uint32                 `protobuf:"varint,4,opt,name=max_mb,json=maxMb,proto3" json:"max_mb,omitempty"`
	DirBuckets     string                 `protobuf:"bytes,5,opt,name=dir_buckets,json=dirBuckets,proto3" json:"dir_buckets,omitempty"`
	Cipher         bool                   `protobuf:"varint,6,opt,name=cipher,proto3" json:"cipher,omitempty"`
	Signatures     []string               `protobuf:"bytes,7,rep,name=signatures,proto3" json:"signatures,omitempty"`
	MetricsAddress string                 `protobuf:"bytes,8,opt,name=metrics_address,json=metricsAddress,proto3" json:"metrics_address,omitempty"`
	FilerGroup     string                 `protobuf:"bytes,9,opt,name=filer_group,json=filerGroup,proto3" json:"filer_group,omitempty"`
	DataCenter     string                 `protobuf:"bytes,10,opt,name=data_center,json=dataCenter,proto3" json:"data_center,omitempty"`
	Rack           string                 `protobuf:"bytes,11,opt,name=rack,proto3" json:"rack,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetFilerConfigurationResponse) Reset() {
	*x = GetFilerConfigurationResponse{}
	mi := &file_filer_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFilerConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilerConfigurationResponse) ProtoMessage() {}

func (x *GetFilerConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilerConfigurationResponse.ProtoReflect.Descriptor instead.
func (*GetFilerConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{36}
}

func (x *GetFilerConfigurationResponse) GetMasters() string {
	if x != nil {
		return x.Masters
	}
	return ""
}

func (x *GetFilerConfigurationResponse) GetReplication() string {
	if x != nil {
		return x.Replication
	}
	return ""
}

func (x *GetFilerConfigurationResponse) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *GetFilerConfigurationResponse) GetMaxMb() uint32 {
	if x != nil {
		return x.MaxMb
	}
	return 0
}

func (x *GetFilerConfigurationResponse) GetDirBuckets() string {
	if x != nil {
		return x.DirBuckets
	}
	return ""
}

func (x *GetFilerConfigurationResponse) GetCipher() bool {
	if x != nil {
		return x.Cipher
	}
	return false
}

func (x *GetFilerConfigurationResponse) GetSignatures() []string {
	if x != nil {
		return x.Signatures
	}
	return nil
}

func (x *GetFilerConfigurationResponse) GetMetricsAddress() string {
	if x != nil {
		return x.MetricsAddress
	}
	return ""
}

func (x *GetFilerConfigurationResponse) GetFilerGroup() string {
	if x != nil {
		return x.FilerGroup
	}
	return ""
}

func (x *GetFilerConfigurationResponse) GetDataCenter() string {
	if x != nil {
		return x.DataCenter
	}
	return ""
}

func (x *GetFilerConfigurationResponse) GetRack() string {
	if x != nil {
		return x.Rack
	}
	return ""
}

type DistributedLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ExpireNs      int64                  `protobuf:"varint,2,opt,name=expire_ns,json=expireNs,proto3" json:"expire_ns,omitempty"`
	RenewToken    string                 `protobuf:"bytes,3,opt,name=renew_token,json=renewToken,proto3" json:"renew_token,omitempty"`
	Owner         string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistributedLockRequest) Reset() {
	*x = DistributedLockRequest{}
	mi := &file_filer_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistributedLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistributedLockRequest) ProtoMessage() {}

func (x *DistributedLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistributedLockRequest.ProtoReflect.Descriptor instead.
func (*DistributedLockRequest) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{37}
}

func (x *DistributedLockRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DistributedLockRequest) GetExpireNs() int64 {
	if x != nil {
		return x.ExpireNs
	}
	return 0
}

func (x *DistributedLockRequest) GetRenewToken() string {
	if x != nil {
		return x.RenewToken
	}
	return ""
}

func (x *DistributedLockRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type DistributedLockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RenewToken    string                 `protobuf:"bytes,1,opt,name=renew_token,json=renewToken,proto3" json:"renew_token,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistributedLockResponse) Reset() {
	*x = DistributedLockResponse{}
	mi := &file_filer_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistributedLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistributedLockResponse) ProtoMessage() {}

func (x *DistributedLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistributedLockResponse.ProtoReflect.Descriptor instead.
func (*DistributedLockResponse) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{38}
}

func (x *DistributedLockResponse) GetRenewToken() string {
	if x != nil {
		return x.RenewToken
	}
	return ""
}

func (x *DistributedLockResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DistributedUnlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RenewToken    string                 `protobuf:"bytes,2,opt,name=renew_token,json=renewToken,proto3" json:"renew_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistributedUnlockRequest) Reset() {
	*x = DistributedUnlockRequest{}
	mi := &file_filer_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistributedUnlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistributedUnlockRequest) ProtoMessage() {}

func (x *DistributedUnlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistributedUnlockRequest.ProtoReflect.Descriptor instead.
func (*DistributedUnlockRequest) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{39}
}

func (x *DistributedUnlockRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DistributedUnlockRequest) GetRenewToken() string {
	if x != nil {
		return x.RenewToken
	}
	return ""
}

type DistributedUnlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistributedUnlockResponse) Reset() {
	*x = DistributedUnlockResponse{}
	mi := &file_filer_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistributedUnlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistributedUnlockResponse) ProtoMessage() {}

func (x *DistributedUnlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filer_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistributedUnlockResponse.ProtoReflect.Descriptor instead.
func (*DistributedUnlockResponse) Descriptor() ([]byte, []int) {
	return file_filer_proto_rawDescGZIP(), []int{40}
}

func (x *DistributedUnlockResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_filer_proto protoreflect.FileDescriptor

const file_filer_proto_rawDesc = "" +
	"\n" +
	"\vfiler.proto\x12\bfiler_pb\"\xb4\x03\n" +
	"\x05Entry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fis_directory\x18\x02 \x01(\bR\visDirectory\x12+\n" +
	"\x06chunks\x18\x03 \x03(\v2\x13.filer_pb.FileChunkR\x06chunks\x128\n" +
	"\n" +
	"attributes\x18\x04 \x01(\v2\x18.filer_pb.FuseAttributesR\n" +
	"attributes\x129\n" +
	"\bextended\x18\x05 \x03(\v2\x1d.filer_pb.Entry.ExtendedEntryR\bextended\x12\x18\n" +
	"\acontent\x18\x06 \x01(\fR\acontent\x12 \n" +
	"\fhard_link_id\x18\a \x01(\fR\n" +
	"hardLinkId\x12*\n" +
	"\x11hard_link_counter\x18\b \x01(\x05R\x0fhardLinkCounter\x12-\n" +
	"\x06remote\x18\t \x01(\v2\x15.filer_pb.RemoteEntryR\x06remote\x1a;\n" +
	"\rExtendedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\x8d\x02\n" +
	"\tFileChunk\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x12$\n" +
	"\x0emodified_ts_ns\x18\x04 \x01(\x03R\fmodifiedTsNs\x12\x13\n" +
	"\x05e_tag\x18\x05 \x01(\tR\x04eTag\x12\x1d\n" +
	"\n" +
	"cipher_key\x18\x06 \x01(\fR\tcipherKey\x12#\n" +
	"\ris_compressed\x18\a \x01(\bR\fisCompressed\x12*\n" +
	"\x11is_chunk_manifest\x18\b \x01(\bR\x0fisChunkManifest\x12\x10\n" +
	"\x03fid\x18\t \x01(\tR\x03fid\"\xd2\x03\n" +
	"\x0eFuseAttributes\x12\x1b\n" +
	"\tfile_size\x18\x01 \x01(\x04R\bfileSize\x12\x14\n" +
	"\x05mtime\x18\x02 \x01(\x03R\x05mtime\x12\x1b\n" +
	"\tfile_mode\x18\x03 \x01(\rR\bfileMode\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\x05 \x01(\rR\x03gid\x12\x16\n" +
	"\x06crtime\x18\x06 \x01(\x03R\x06crtime\x12\x12\n" +
	"\x04mime\x18\a \x01(\tR\x04mime\x12 \n" +
	"\vreplication\x18\b \x01(\tR\vreplication\x12\x1e\n" +
	"\n" +
	"collection\x18\t \x01(\tR\n" +
	"collection\x12\x17\n" +
	"\attl_sec\x18\n" +
	" \x01(\x05R\x06ttlSec\x12\x1b\n" +
	"\tuser_name\x18\v \x01(\tR\buserName\x12\x1f\n" +
	"\vgroup_names\x18\f \x03(\tR\n" +
	"groupNames\x12%\n" +
	"\x0esymlink_target\x18\r \x01(\tR\rsymlinkTarget\x12\x10\n" +
	"\x03md5\x18\x0e \x01(\tR\x03md5\x12\x1b\n" +
	"\tdisk_type\x18\x0f \x01(\tR\bdiskType\x12\x1b\n" +
	"\tis_remote\x18\x10 \x01(\bR\bisRemote\x12\x14\n" +
	"\x05inode\x18\x11 \x01(\x04R\x05inode\"\xc6\x01\n" +
	"\vRemoteEntry\x12!\n" +
	"\fstorage_name\x18\x01 \x01(\tR\vstorageName\x12\x1f\n" +
	"\vremote_path\x18\x02 \x01(\tR\n" +
	"remotePath\x12\x1f\n" +
	"\vremote_size\x18\x03 \x01(\x03R\n" +
	"remoteSize\x12 \n" +
	"\fremote_e_tag\x18\x04 \x01(\tR\n" +
	"remoteETag\x120\n" +
	"\x15last_local_sync_ts_ns\x18\x05 \x01(\x03R\x11lastLocalSyncTsNs\"O\n" +
	"\x1bLookupDirectoryEntryRequest\x12\x1c\n" +
	"\tdirectory\x18\x01 \x01(\tR\tdirectory\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"[\n" +
	"\x1cLookupDirectoryEntryResponse\x12%\n" +
	"\x05entry\x18\x01 \x01(\v2\x0f.filer_pb.EntryR\x05entry\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xc3\x01\n" +
	"\x12ListEntriesRequest\x12\x1c\n" +
	"\tdirectory\x18\x01 \x01(\tR\tdirectory\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12/\n" +
	"\x14start_from_file_name\x18\x03 \x01(\tR\x11startFromFileName\x120\n" +
	"\x14inclusive_start_from\x18\x04 \x01(\bR\x12inclusiveStartFrom\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\rR\x05limit\"<\n" +
	"\x13ListEntriesResponse\x12%\n" +
	"\x05entry\x18\x01 \x01(\v2\x0f.filer_pb.EntryR\x05entry\"\xf6\x01\n" +
	"\x12CreateEntryRequest\x12\x1c\n" +
	"\tdirectory\x18\x01 \x01(\tR\tdirectory\x12%\n" +
	"\x05entry\x18\x02 \x01(\v2\x0f.filer_pb.EntryR\x05entry\x12\x15\n" +
	"\x06o_excl\x18\x03 \x01(\bR\x05oExcl\x121\n" +
	"\x15is_from_other_cluster\x18\x04 \x01(\bR\x12isFromOtherCluster\x12\x1e\n" +
	"\n" +
	"signatures\x18\x05 \x03(\tR\n" +
	"signatures\x121\n" +
	"\x15skip_check_parent_dir\x18\x06 \x01(\bR\x12skipCheckParentDir\"+\n" +
	"\x13CreateEntryResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\xac\x01\n" +
	"\x12UpdateEntryRequest\x12\x1c\n" +
	"\tdirectory\x18\x01 \x01(\tR\tdirectory\x12%\n" +
	"\x05entry\x18\x02 \x01(\v2\x0f.filer_pb.EntryR\x05entry\x121\n" +
	"\x15is_from_other_cluster\x18\x03 \x01(\bR\x12isFromOtherCluster\x12\x1e\n" +
	"\n" +
	"signatures\x18\x04 \x03(\tR\n" +
	"signatures\"+\n" +
	"\x13UpdateEntryResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\x80\x01\n" +
	"\x14AppendToEntryRequest\x12\x1c\n" +
	"\tdirectory\x18\x01 \x01(\tR\tdirectory\x12\x1d\n" +
	"\n" +
	"entry_name\x18\x02 \x01(\tR\tentryName\x12+\n" +
	"\x06chunks\x18\x03 \x03(\v2\x13.filer_pb.FileChunkR\x06chunks\"-\n" +
	"\x15AppendToEntryResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\xc5\x02\n" +
	"\x12DeleteEntryRequest\x12\x1c\n" +
	"\tdirectory\x18\x01 \x01(\tR\tdirectory\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12$\n" +
	"\x0eis_delete_data\x18\x03 \x01(\bR\fisDeleteData\x12!\n" +
	"\fis_recursive\x18\x04 \x01(\bR\visRecursive\x124\n" +
	"\x16ignore_recursive_error\x18\x05 \x01(\bR\x14ignoreRecursiveError\x121\n" +
	"\x15is_from_other_cluster\x18\x06 \x01(\bR\x12isFromOtherCluster\x12\x1e\n" +
	"\n" +
	"signatures\x18\a \x03(\tR\n" +
	"signatures\x12+\n" +
	"\x06chunks\x18\b \x03(\v2\x13.filer_pb.FileChunkR\x06chunks\"+\n" +
	"\x13DeleteEntryResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\x9a\x01\n" +
	"\x18AtomicRenameEntryRequest\x12#\n" +
	"\rold_directory\x18\x01 \x01(\tR\foldDirectory\x12\x19\n" +
	"\bold_name\x18\x02 \x01(\tR\aoldName\x12#\n" +
	"\rnew_directory\x18\x03 \x01(\tR\fnewDirectory\x12\x19\n" +
	"\bnew_name\x18\x04 \x01(\tR\anewName\"1\n" +
	"\x19AtomicRenameEntryResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\xba\x01\n" +
	"\x18StreamRenameEntryRequest\x12#\n" +
	"\rold_directory\x18\x01 \x01(\tR\foldDirectory\x12\x19\n" +
	"\bold_name\x18\x02 \x01(\tR\aoldName\x12#\n" +
	"\rnew_directory\x18\x03 \x01(\tR\fnewDirectory\x12\x19\n" +
	"\bnew_name\x18\x04 \x01(\tR\anewName\x12\x1e\n" +
	"\n" +
	"signatures\x18\x05 \x03(\tR\n" +
	"signatures\"\x99\x01\n" +
	"\x19StreamRenameEntryResponse\x12%\n" +
	"\x05entry\x18\x01 \x01(\v2\x0f.filer_pb.EntryR\x05entry\x12-\n" +
	"\x12event_notification\x18\x02 \x01(\tR\x11eventNotification\x12&\n" +
	"\x0fnew_parent_path\x18\x03 \x01(\tR\rnewParentPath\"\xff\x01\n" +
	"\x13AssignVolumeRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\rR\x05count\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12 \n" +
	"\vreplication\x18\x03 \x01(\tR\vreplication\x12\x10\n" +
	"\x03ttl\x18\x04 \x01(\tR\x03ttl\x12\x1b\n" +
	"\tdisk_type\x18\x05 \x01(\tR\bdiskType\x12\x1f\n" +
	"\vdata_center\x18\x06 \x01(\tR\n" +
	"dataCenter\x12\x12\n" +
	"\x04rack\x18\a \x01(\tR\x04rack\x12,\n" +
	"\x12replication_as_min\x18\b \x01(\x05R\x10replicationAsMin\"\x91\x02\n" +
	"\x14AssignVolumeResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"public_url\x18\x03 \x01(\tR\tpublicUrl\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\x12\x12\n" +
	"\x04auth\x18\x05 \x01(\tR\x04auth\x12\x1e\n" +
	"\n" +
	"collection\x18\x06 \x01(\tR\n" +
	"collection\x12 \n" +
	"\vreplication\x18\a \x01(\tR\vreplication\x12\x10\n" +
	"\x03ttl\x18\b \x01(\tR\x03ttl\x12\x1b\n" +
	"\tdisk_type\x18\t \x01(\tR\bdiskType\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\"4\n" +
	"\x13LookupVolumeRequest\x12\x1d\n" +
	"\n" +
	"volume_ids\x18\x01 \x03(\tR\tvolumeIds\"\xc3\x01\n" +
	"\x14LookupVolumeResponse\x12U\n" +
	"\rlocations_map\x18\x01 \x03(\v20.filer_pb.LookupVolumeResponse.LocationsMapEntryR\flocationsMap\x1aT\n" +
	"\x11LocationsMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.filer_pb.LocationsR\x05value:\x028\x01\"S\n" +
	"\tLocations\x120\n" +
	"\tlocations\x18\x01 \x03(\v2\x12.filer_pb.LocationR\tlocations\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\\\n" +
	"\bLocation\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"public_url\x18\x02 \x01(\tR\tpublicUrl\x12\x1f\n" +
	"\vdata_center\x18\x03 \x01(\tR\n" +
	"dataCenter\"\xbb\x01\n" +
	"\x18SubscribeMetadataRequest\x12\x1f\n" +
	"\vpath_prefix\x18\x01 \x01(\tR\n" +
	"pathPrefix\x12\x19\n" +
	"\bsince_ns\x18\x02 \x01(\x03R\asinceNs\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\x05R\bclientId\x12\x1f\n" +
	"\vclient_name\x18\x04 \x01(\tR\n" +
	"clientName\x12%\n" +
	"\x0ewatched_events\x18\x05 \x03(\tR\rwatchedEvents\"\x9a\x01\n" +
	"\x19SubscribeMetadataResponse\x12\x1c\n" +
	"\tdirectory\x18\x01 \x01(\tR\tdirectory\x12J\n" +
	"\x12event_notification\x18\x02 \x01(\v2\x1b.filer_pb.EventNotificationR\x11eventNotification\x12\x13\n" +
	"\x05ts_ns\x18\x03 \x01(\x03R\x04tsNs\"\xb0\x02\n" +
	"\x11EventNotification\x12,\n" +
	"\told_entry\x18\x01 \x01(\v2\x0f.filer_pb.EntryR\boldEntry\x12,\n" +
	"\tnew_entry\x18\x02 \x01(\v2\x0f.filer_pb.EntryR\bnewEntry\x12#\n" +
	"\rdelete_chunks\x18\x03 \x01(\bR\fdeleteChunks\x12&\n" +
	"\x0fnew_parent_path\x18\x04 \x01(\tR\rnewParentPath\x121\n" +
	"\x15is_from_other_cluster\x18\x05 \x01(\bR\x12isFromOtherCluster\x12\x1e\n" +
	"\n" +
	"signatures\x18\x06 \x03(\tR\n" +
	"signatures\x12\x1f\n" +
	"\vis_truncate\x18\a \x01(\bR\n" +
	"isTruncate\" \n" +
	"\fKvGetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\";\n" +
	"\rKvGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"6\n" +
	"\fKvPutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"%\n" +
	"\rKvPutResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"#\n" +
	"\x0fKvDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"(\n" +
	"\x10KvDeleteResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\x1e\n" +
	"\x1cGetFilerConfigurationRequest\"\xea\x02\n" +
	"\x1dGetFilerConfigurationResponse\x12\x18\n" +
	"\amasters\x18\x01 \x01(\tR\amasters\x12 \n" +
	"\vreplication\x18\x02 \x01(\tR\vreplication\x12\x1e\n" +
	"\n" +
	"collection\x18\x03 \x01(\tR\n" +
	"collection\x12\x15\n" +
	"\x06max_mb\x18\x04 \x01(\rR\x05maxMb\x12\x1f\n" +
	"\vdir_buckets\x18\x05 \x01(\tR\n" +
	"dirBuckets\x12\x16\n" +
	"\x06cipher\x18\x06 \x01(\bR\x06cipher\x12\x1e\n" +
	"\n" +
	"signatures\x18\a \x03(\tR\n" +
	"signatures\x12'\n" +
	"\x0fmetrics_address\x18\b \x01(\tR\x0emetricsAddress\x12\x1f\n" +
	"\vfiler_group\x18\t \x01(\tR\n" +
	"filerGroup\x12\x1f\n" +
	"\vdata_center\x18\n" +
	" \x01(\tR\n" +
	"dataCenter\x12\x12\n" +
	"\x04rack\x18\v \x01(\tR\x04rack\"\x80\x01\n" +
	"\x16DistributedLockRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\texpire_ns\x18\x02 \x01(\x03R\bexpireNs\x12\x1f\n" +
	"\vrenew_token\x18\x03 \x01(\tR\n" +
	"renewToken\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\"P\n" +
	"\x17DistributedLockResponse\x12\x1f\n" +
	"\vrenew_token\x18\x01 \x01(\tR\n" +
	"renewToken\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"O\n" +
	"\x18DistributedUnlockRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vrenew_token\x18\x02 \x01(\tR\n" +
	"renewToken\"1\n" +
	"\x19DistributedUnlockResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error2\x95\f\n" +
	"\fFilerService\x12g\n" +
	"\x14LookupDirectoryEntry\x12%.filer_pb.LookupDirectoryEntryRequest\x1a&.filer_pb.LookupDirectoryEntryResponse\"\x00\x12N\n" +
	"\vListEntries\x12\x1c.filer_pb.ListEntriesRequest\x1a\x1d.filer_pb.ListEntriesResponse\"\x000\x01\x12L\n" +
	"\vCreateEntry\x12\x1c.filer_pb.CreateEntryRequest\x1a\x1d.filer_pb.CreateEntryResponse\"\x00\x12L\n" +
	"\vUpdateEntry\x12\x1c.filer_pb.UpdateEntryRequest\x1a\x1d.filer_pb.UpdateEntryResponse\"\x00\x12R\n" +
	"\rAppendToEntry\x12\x1e.filer_pb.AppendToEntryRequest\x1a\x1f.filer_pb.AppendToEntryResponse\"\x00\x12L\n" +
	"\vDeleteEntry\x12\x1c.filer_pb.DeleteEntryRequest\x1a\x1d.filer_pb.DeleteEntryResponse\"\x00\x12^\n" +
	"\x11AtomicRenameEntry\x12\".filer_pb.AtomicRenameEntryRequest\x1a#.filer_pb.AtomicRenameEntryResponse\"\x00\x12`\n" +
	"\x11StreamRenameEntry\x12\".filer_pb.StreamRenameEntryRequest\x1a#.filer_pb.StreamRenameEntryResponse\"\x000\x01\x12O\n" +
	"\fAssignVolume\x12\x1d.filer_pb.AssignVolumeRequest\x1a\x1e.filer_pb.AssignVolumeResponse\"\x00\x12O\n" +
	"\fLookupVolume\x12\x1d.filer_pb.LookupVolumeRequest\x1a\x1e.filer_pb.LookupVolumeResponse\"\x00\x12`\n" +
	"\x11SubscribeMetadata\x12\".filer_pb.SubscribeMetadataRequest\x1a#.filer_pb.SubscribeMetadataResponse\"\x000\x01\x12e\n" +
	"\x16SubscribeLocalMetadata\x12\".filer_pb.SubscribeMetadataRequest\x1a#.filer_pb.SubscribeMetadataResponse\"\x000\x01\x12:\n" +
	"\x05KvGet\x12\x16.filer_pb.KvGetRequest\x1a\x17.filer_pb.KvGetResponse\"\x00\x12:\n" +
	"\x05KvPut\x12\x16.filer_pb.KvPutRequest\x1a\x17.filer_pb.KvPutResponse\"\x00\x12C\n" +
	"\bKvDelete\x12\x19.filer_pb.KvDeleteRequest\x1a\x1a.filer_pb.KvDeleteResponse\"\x00\x12j\n" +
	"\x15GetFilerConfiguration\x12&.filer_pb.GetFilerConfigurationRequest\x1a'.filer_pb.GetFilerConfigurationResponse\"\x00\x12X\n" +
	"\x0fDistributedLock\x12 .filer_pb.DistributedLockRequest\x1a!.filer_pb.DistributedLockResponse\"\x00\x12^\n" +
	"\x11DistributedUnlock\x12\".filer_pb.DistributedUnlockRequest\x1a#.filer_pb.DistributedUnlockResponse\"\x00B\x14Z\x12goblob/pb/filer_pbb\x06proto3"

var (
	file_filer_proto_rawDescOnce sync.Once
	file_filer_proto_rawDescData []byte
)

func file_filer_proto_rawDescGZIP() []byte {
	file_filer_proto_rawDescOnce.Do(func() {
		file_filer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_filer_proto_rawDesc), len(file_filer_proto_rawDesc)))
	})
	return file_filer_proto_rawDescData
}

var file_filer_proto_msgTypes = make([]protoimpl.MessageInfo, 43)
var file_filer_proto_goTypes = []any{
	(*Entry)(nil),                         // 0: filer_pb.Entry
	(*FileChunk)(nil),                     // 1: filer_pb.FileChunk
	(*FuseAttributes)(nil),                // 2: filer_pb.FuseAttributes
	(*RemoteEntry)(nil),                   // 3: filer_pb.RemoteEntry
	(*LookupDirectoryEntryRequest)(nil),   // 4: filer_pb.LookupDirectoryEntryRequest
	(*LookupDirectoryEntryResponse)(nil),  // 5: filer_pb.LookupDirectoryEntryResponse
	(*ListEntriesRequest)(nil),            // 6: filer_pb.ListEntriesRequest
	(*ListEntriesResponse)(nil),           // 7: filer_pb.ListEntriesResponse
	(*CreateEntryRequest)(nil),            // 8: filer_pb.CreateEntryRequest
	(*CreateEntryResponse)(nil),           // 9: filer_pb.CreateEntryResponse
	(*UpdateEntryRequest)(nil),            // 10: filer_pb.UpdateEntryRequest
	(*UpdateEntryResponse)(nil),           // 11: filer_pb.UpdateEntryResponse
	(*AppendToEntryRequest)(nil),          // 12: filer_pb.AppendToEntryRequest
	(*AppendToEntryResponse)(nil),         // 13: filer_pb.AppendToEntryResponse
	(*DeleteEntryRequest)(nil),            // 14: filer_pb.DeleteEntryRequest
	(*DeleteEntryResponse)(nil),           // 15: filer_pb.DeleteEntryResponse
	(*AtomicRenameEntryRequest)(nil),      // 16: filer_pb.AtomicRenameEntryRequest
	(*AtomicRenameEntryResponse)(nil),     // 17: filer_pb.AtomicRenameEntryResponse
	(*StreamRenameEntryRequest)(nil),      // 18: filer_pb.StreamRenameEntryRequest
	(*StreamRenameEntryResponse)(nil),     // 19: filer_pb.StreamRenameEntryResponse
	(*AssignVolumeRequest)(nil),           // 20: filer_pb.AssignVolumeRequest
	(*AssignVolumeResponse)(nil),          // 21: filer_pb.AssignVolumeResponse
	(*LookupVolumeRequest)(nil),           // 22: filer_pb.LookupVolumeRequest
	(*LookupVolumeResponse)(nil),          // 23: filer_pb.LookupVolumeResponse
	(*Locations)(nil),                     // 24: filer_pb.Locations
	(*Location)(nil),                      // 25: filer_pb.Location
	(*SubscribeMetadataRequest)(nil),      // 26: filer_pb.SubscribeMetadataRequest
	(*SubscribeMetadataResponse)(nil),     // 27: filer_pb.SubscribeMetadataResponse
	(*EventNotification)(nil),             // 28: filer_pb.EventNotification
	(*KvGetRequest)(nil),                  // 29: filer_pb.KvGetRequest
	(*KvGetResponse)(nil),                 // 30: filer_pb.KvGetResponse
	(*KvPutRequest)(nil),                  // 31: filer_pb.KvPutRequest
	(*KvPutResponse)(nil),                 // 32: filer_pb.KvPutResponse
	(*KvDeleteRequest)(nil),               // 33: filer_pb.KvDeleteRequest
	(*KvDeleteResponse)(nil),              // 34: filer_pb.KvDeleteResponse
	(*GetFilerConfigurationRequest)(nil),  // 35: filer_pb.GetFilerConfigurationRequest
	(*GetFilerConfigurationResponse)(nil), // 36: filer_pb.GetFilerConfigurationResponse
	(*DistributedLockRequest)(nil),        // 37: filer_pb.DistributedLockRequest
	(*DistributedLockResponse)(nil),       // 38: filer_pb.DistributedLockResponse
	(*DistributedUnlockRequest)(nil),      // 39: filer_pb.DistributedUnlockRequest
	(*DistributedUnlockResponse)(nil),     // 40: filer_pb.DistributedUnlockResponse
	nil,                                   // 41: filer_pb.Entry.ExtendedEntry
	nil,                                   // 42: filer_pb.LookupVolumeResponse.LocationsMapEntry
}
var file_filer_proto_depIdxs = []int32{
	1,  // 0: filer_pb.Entry.chunks:type_name -> filer_pb.FileChunk
	2,  // 1: filer_pb.Entry.attributes:type_name -> filer_pb.FuseAttributes
	41, // 2: filer_pb.Entry.extended:type_name -> filer_pb.Entry.ExtendedEntry
	3,  // 3: filer_pb.Entry.remote:type_name -> filer_pb.RemoteEntry
	0,  // 4: filer_pb.LookupDirectoryEntryResponse.entry:type_name -> filer_pb.Entry
	0,  // 5: filer_pb.ListEntriesResponse.entry:type_name -> filer_pb.Entry
	0,  // 6: filer_pb.CreateEntryRequest.entry:type_name -> filer_pb.Entry
	0,  // 7: filer_pb.UpdateEntryRequest.entry:type_name -> filer_pb.Entry
	1,  // 8: filer_pb.AppendToEntryRequest.chunks:type_name -> filer_pb.FileChunk
	1,  // 9: filer_pb.DeleteEntryRequest.chunks:type_name -> filer_pb.FileChunk
	0,  // 10: filer_pb.StreamRenameEntryResponse.entry:type_name -> filer_pb.Entry
	42, // 11: filer_pb.LookupVolumeResponse.locations_map:type_name -> filer_pb.LookupVolumeResponse.LocationsMapEntry
	25, // 12: filer_pb.Locations.locations:type_name -> filer_pb.Location
	28, // 13: filer_pb.SubscribeMetadataResponse.event_notification:type_name -> filer_pb.EventNotification
	0,  // 14: filer_pb.EventNotification.old_entry:type_name -> filer_pb.Entry
	0,  // 15: filer_pb.EventNotification.new_entry:type_name -> filer_pb.Entry
	24, // 16: filer_pb.LookupVolumeResponse.LocationsMapEntry.value:type_name -> filer_pb.Locations
	4,  // 17: filer_pb.FilerService.LookupDirectoryEntry:input_type -> filer_pb.LookupDirectoryEntryRequest
	6,  // 18: filer_pb.FilerService.ListEntries:input_type -> filer_pb.ListEntriesRequest
	8,  // 19: filer_pb.FilerService.CreateEntry:input_type -> filer_pb.CreateEntryRequest
	10, // 20: filer_pb.FilerService.UpdateEntry:input_type -> filer_pb.UpdateEntryRequest
	12, // 21: filer_pb.FilerService.AppendToEntry:input_type -> filer_pb.AppendToEntryRequest
	14, // 22: filer_pb.FilerService.DeleteEntry:input_type -> filer_pb.DeleteEntryRequest
	16, // 23: filer_pb.FilerService.AtomicRenameEntry:input_type -> filer_pb.AtomicRenameEntryRequest
	18, // 24: filer_pb.FilerService.StreamRenameEntry:input_type -> filer_pb.StreamRenameEntryRequest
	20, // 25: filer_pb.FilerService.AssignVolume:input_type -> filer_pb.AssignVolumeRequest
	22, // 26: filer_pb.FilerService.LookupVolume:input_type -> filer_pb.LookupVolumeRequest
	26, // 27: filer_pb.FilerService.SubscribeMetadata:input_type -> filer_pb.SubscribeMetadataRequest
	26, // 28: filer_pb.FilerService.SubscribeLocalMetadata:input_type -> filer_pb.SubscribeMetadataRequest
	29, // 29: filer_pb.FilerService.KvGet:input_type -> filer_pb.KvGetRequest
	31, // 30: filer_pb.FilerService.KvPut:input_type -> filer_pb.KvPutRequest
	33, // 31: filer_pb.FilerService.KvDelete:input_type -> filer_pb.KvDeleteRequest
	35, // 32: filer_pb.FilerService.GetFilerConfiguration:input_type -> filer_pb.GetFilerConfigurationRequest
	37, // 33: filer_pb.FilerService.DistributedLock:input_type -> filer_pb.DistributedLockRequest
	39, // 34: filer_pb.FilerService.DistributedUnlock:input_type -> filer_pb.DistributedUnlockRequest
	5,  // 35: filer_pb.FilerService.LookupDirectoryEntry:output_type -> filer_pb.LookupDirectoryEntryResponse
	7,  // 36: filer_pb.FilerService.ListEntries:output_type -> filer_pb.ListEntriesResponse
	9,  // 37: filer_pb.FilerService.CreateEntry:output_type -> filer_pb.CreateEntryResponse
	11, // 38: filer_pb.FilerService.UpdateEntry:output_type -> filer_pb.UpdateEntryResponse
	13, // 39: filer_pb.FilerService.AppendToEntry:output_type -> filer_pb.AppendToEntryResponse
	15, // 40: filer_pb.FilerService.DeleteEntry:output_type -> filer_pb.DeleteEntryResponse
	17, // 41: filer_pb.FilerService.AtomicRenameEntry:output_type -> filer_pb.AtomicRenameEntryResponse
	19, // 42: filer_pb.FilerService.StreamRenameEntry:output_type -> filer_pb.StreamRenameEntryResponse
	21, // 43: filer_pb.FilerService.AssignVolume:output_type -> filer_pb.AssignVolumeResponse
	23, // 44: filer_pb.FilerService.LookupVolume:output_type -> filer_pb.LookupVolumeResponse
	27, // 45: filer_pb.FilerService.SubscribeMetadata:output_type -> filer_pb.SubscribeMetadataResponse
	27, // 46: filer_pb.FilerService.SubscribeLocalMetadata:output_type -> filer_pb.SubscribeMetadataResponse
	30, // 47: filer_pb.FilerService.KvGet:output_type -> filer_pb.KvGetResponse
	32, // 48: filer_pb.FilerService.KvPut:output_type -> filer_pb.KvPutResponse
	34, // 49: filer_pb.FilerService.KvDelete:output_type -> filer_pb.KvDeleteResponse
	36, // 50: filer_pb.FilerService.GetFilerConfiguration:output_type -> filer_pb.GetFilerConfigurationResponse
	38, // 51: filer_pb.FilerService.DistributedLock:output_type -> filer_pb.DistributedLockResponse
	40, // 52: filer_pb.FilerService.DistributedUnlock:output_type -> filer_pb.DistributedUnlockResponse
	35, // [35:53] is the sub-list for method output_type
	17, // [17:35] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_filer_proto_init() }
func file_filer_proto_init() {
	if File_filer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_filer_proto_rawDesc), len(file_filer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   43,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_filer_proto_goTypes,
		DependencyIndexes: file_filer_proto_depIdxs,
		MessageInfos:      file_filer_proto_msgTypes,
	}.Build()
	File_filer_proto = out.File
	file_filer_proto_goTypes = nil
	file_filer_proto_depIdxs = nil
}
