apiVersion: apps/v1
kind: Deployment
metadata:
  name: goblob-s3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goblob-s3
  template:
    metadata:
      labels:
        app: goblob-s3
    spec:
      containers:
        - name: s3
          image: goblob:latest
          args: ["s3", "-ip=0.0.0.0", "-port=8333", "-filer=goblob-filer:8888", "-metricsPort=9093"]
          ports:
            - containerPort: 8333
            - containerPort: 9093
---
apiVersion: v1
kind: Service
metadata:
  name: goblob-s3
spec:
  selector:
    app: goblob-s3
  ports:
    - name: http
      port: 8333
      targetPort: 8333
