// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: iam.proto

package iam_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetS3ApiConfigurationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetS3ApiConfigurationRequest) Reset() {
	*x = GetS3ApiConfigurationRequest{}
	mi := &file_iam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetS3ApiConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetS3ApiConfigurationRequest) ProtoMessage() {}

func (x *GetS3ApiConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetS3ApiConfigurationRequest.ProtoReflect.Descriptor instead.
func (*GetS3ApiConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{0}
}

type GetS3ApiConfigurationResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	S3ApiConfiguration *S3ApiConfiguration    `protobuf:"bytes,1,opt,name=s3_api_configuration,json=s3ApiConfiguration,proto3" json:"s3_api_configuration,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetS3ApiConfigurationResponse) Reset() {
	*x = GetS3ApiConfigurationResponse{}
	mi := &file_iam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetS3ApiConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetS3ApiConfigurationResponse) ProtoMessage() {}

func (x *GetS3ApiConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetS3ApiConfigurationResponse.ProtoReflect.Descriptor instead.
func (*GetS3ApiConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{1}
}

func (x *GetS3ApiConfigurationResponse) GetS3ApiConfiguration() *S3ApiConfiguration {
	if x != nil {
		return x.S3ApiConfiguration
	}
	return nil
}

type PutS3ApiConfigurationRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	S3ApiConfiguration *S3ApiConfiguration    `protobuf:"bytes,1,opt,name=s3_api_configuration,json=s3ApiConfiguration,proto3" json:"s3_api_configuration,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PutS3ApiConfigurationRequest) Reset() {
	*x = PutS3ApiConfigurationRequest{}
	mi := &file_iam_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutS3ApiConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutS3ApiConfigurationRequest) ProtoMessage() {}

func (x *PutS3ApiConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutS3ApiConfigurationRequest.ProtoReflect.Descriptor instead.
func (*PutS3ApiConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{2}
}

func (x *PutS3ApiConfigurationRequest) GetS3ApiConfiguration() *S3ApiConfiguration {
	if x != nil {
		return x.S3ApiConfiguration
	}
	return nil
}

type PutS3ApiConfigurationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutS3ApiConfigurationResponse) Reset() {
	*x = PutS3ApiConfigurationResponse{}
	mi := &file_iam_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutS3ApiConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutS3ApiConfigurationResponse) ProtoMessage() {}

func (x *PutS3ApiConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutS3ApiConfigurationResponse.ProtoReflect.Descriptor instead.
func (*PutS3ApiConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{3}
}

func (x *PutS3ApiConfigurationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetS3ApiConfigurationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetS3ApiConfigurationsRequest) Reset() {
	*x = GetS3ApiConfigurationsRequest{}
	mi := &file_iam_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetS3ApiConfigurationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetS3ApiConfigurationsRequest) ProtoMessage() {}

func (x *GetS3ApiConfigurationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetS3ApiConfigurationsRequest.ProtoReflect.Descriptor instead.
func (*GetS3ApiConfigurationsRequest) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{4}
}

type GetS3ApiConfigurationsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	S3ApiConfiguration *S3ApiConfiguration    `protobuf:"bytes,1,opt,name=s3_api_configuration,json=s3ApiConfiguration,proto3" json:"s3_api_configuration,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetS3ApiConfigurationsResponse) Reset() {
	*x = GetS3ApiConfigurationsResponse{}
	mi := &file_iam_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetS3ApiConfigurationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetS3ApiConfigurationsResponse) ProtoMessage() {}

func (x *GetS3ApiConfigurationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetS3ApiConfigurationsResponse.ProtoReflect.Descriptor instead.
func (*GetS3ApiConfigurationsResponse) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{5}
}

func (x *GetS3ApiConfigurationsResponse) GetS3ApiConfiguration() *S3ApiConfiguration {
	if x != nil {
		return x.S3ApiConfiguration
	}
	return nil
}

type S3ApiConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identities    []*Identity            `protobuf:"bytes,1,rep,name=identities,proto3" json:"identities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S3ApiConfiguration) Reset() {
	*x = S3ApiConfiguration{}
	mi := &file_iam_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3ApiConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3ApiConfiguration) ProtoMessage() {}

func (x *S3ApiConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3ApiConfiguration.ProtoReflect.Descriptor instead.
func (*S3ApiConfiguration) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{6}
}

func (x *S3ApiConfiguration) GetIdentities() []*Identity {
	if x != nil {
		return x.Identities
	}
	return nil
}

type Identity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Credentials   []*Credential          `protobuf:"bytes,2,rep,name=credentials,proto3" json:"credentials,omitempty"`
	Actions       []string               `protobuf:"bytes,3,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_iam_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{7}
}

func (x *Identity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Identity) GetCredentials() []*Credential {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *Identity) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

type Credential struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessKey     string                 `protobuf:"bytes,1,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SecretKey     string                 `protobuf:"bytes,2,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credential) Reset() {
	*x = Credential{}
	mi := &file_iam_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credential) ProtoMessage() {}

func (x *Credential) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credential.ProtoReflect.Descriptor instead.
func (*Credential) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{8}
}

func (x *Credential) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *Credential) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

var File_iam_proto protoreflect.FileDescriptor

const file_iam_proto_rawDesc = "" +
	"\n" +
	"\tiam.proto\x12\x06iam_pb\"\x1e\n" +
	"\x1cGetS3ApiConfigurationRequest\"m\n" +
	"\x1dGetS3ApiConfigurationResponse\x12L\n" +
	"\x14s3_api_configuration\x18\x01 \x01(\v2\x1a.iam_pb.S3ApiConfigurationR\x12s3ApiConfiguration\"l\n" +
	"\x1cPutS3ApiConfigurationRequest\x12L\n" +
	"\x14s3_api_configuration\x18\x01 \x01(\v2\x1a.iam_pb.S3ApiConfigurationR\x12s3ApiConfiguration\"5\n" +
	"\x1dPutS3ApiConfigurationResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\x1f\n" +
	"\x1dGetS3ApiConfigurationsRequest\"n\n" +
	"\x1eGetS3ApiConfigurationsResponse\x12L\n" +
	"\x14s3_api_configuration\x18\x01 \x01(\v2\x1a.iam_pb.S3ApiConfigurationR\x12s3ApiConfiguration\"F\n" +
	"\x12S3ApiConfiguration\x120\n" +
	"\n" +
	"identities\x18\x01 \x03(\v2\x10.iam_pb.IdentityR\n" +
	"identities\"n\n" +
	"\bIdentity\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x124\n" +
	"\vcredentials\x18\x02 \x03(\v2\x12.iam_pb.CredentialR\vcredentials\x12\x18\n" +
	"\aactions\x18\x03 \x03(\tR\aactions\"J\n" +
	"\n" +
	"Credential\x12\x1d\n" +
	"\n" +
	"access_key\x18\x01 \x01(\tR\taccessKey\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x02 \x01(\tR\tsecretKey2\xc9\x02\n" +
	"\n" +
	"IAMService\x12f\n" +
	"\x15GetS3ApiConfiguration\x12$.iam_pb.GetS3ApiConfigurationRequest\x1a%.iam_pb.GetS3ApiConfigurationResponse\"\x00\x12f\n" +
	"\x15PutS3ApiConfiguration\x12$.iam_pb.PutS3ApiConfigurationRequest\x1a%.iam_pb.PutS3ApiConfigurationResponse\"\x00\x12k\n" +
	"\x16GetS3ApiConfigurations\x12%.iam_pb.GetS3ApiConfigurationsRequest\x1a&.iam_pb.GetS3ApiConfigurationsResponse\"\x000\x01B\x12Z\x10goblob/pb/iam_pbb\x06proto3"

var (
	file_iam_proto_rawDescOnce sync.Once
	file_iam_proto_rawDescData []byte
)

func file_iam_proto_rawDescGZIP() []byte {
	file_iam_proto_rawDescOnce.Do(func() {
		file_iam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iam_proto_rawDesc), len(file_iam_proto_rawDesc)))
	})
	return file_iam_proto_rawDescData
}

var file_iam_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_iam_proto_goTypes = []any{
	(*GetS3ApiConfigurationRequest)(nil),   // 0: iam_pb.GetS3ApiConfigurationRequest
	(*GetS3ApiConfigurationResponse)(nil),  // 1: iam_pb.GetS3ApiConfigurationResponse
	(*PutS3ApiConfigurationRequest)(nil),   // 2: iam_pb.PutS3ApiConfigurationRequest
	(*PutS3ApiConfigurationResponse)(nil),  // 3: iam_pb.PutS3ApiConfigurationResponse
	(*GetS3ApiConfigurationsRequest)(nil),  // 4: iam_pb.GetS3ApiConfigurationsRequest
	(*GetS3ApiConfigurationsResponse)(nil), // 5: iam_pb.GetS3ApiConfigurationsResponse
	(*S3ApiConfiguration)(nil),             // 6: iam_pb.S3ApiConfiguration
	(*Identity)(nil),                       // 7: iam_pb.Identity
	(*Credential)(nil),                     // 8: iam_pb.Credential
}
var file_iam_proto_depIdxs = []int32{
	6, // 0: iam_pb.GetS3ApiConfigurationResponse.s3_api_configuration:type_name -> iam_pb.S3ApiConfiguration
	6, // 1: iam_pb.PutS3ApiConfigurationRequest.s3_api_configuration:type_name -> iam_pb.S3ApiConfiguration
	6, // 2: iam_pb.GetS3ApiConfigurationsResponse.s3_api_configuration:type_name -> iam_pb.S3ApiConfiguration
	7, // 3: iam_pb.S3ApiConfiguration.identities:type_name -> iam_pb.Identity
	8, // 4: iam_pb.Identity.credentials:type_name -> iam_pb.Credential
	0, // 5: iam_pb.IAMService.GetS3ApiConfiguration:input_type -> iam_pb.GetS3ApiConfigurationRequest
	2, // 6: iam_pb.IAMService.PutS3ApiConfiguration:input_type -> iam_pb.PutS3ApiConfigurationRequest
	4, // 7: iam_pb.IAMService.GetS3ApiConfigurations:input_type -> iam_pb.GetS3ApiConfigurationsRequest
	1, // 8: iam_pb.IAMService.GetS3ApiConfiguration:output_type -> iam_pb.GetS3ApiConfigurationResponse
	3, // 9: iam_pb.IAMService.PutS3ApiConfiguration:output_type -> iam_pb.PutS3ApiConfigurationResponse
	5, // 10: iam_pb.IAMService.GetS3ApiConfigurations:output_type -> iam_pb.GetS3ApiConfigurationsResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_iam_proto_init() }
func file_iam_proto_init() {
	if File_iam_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iam_proto_rawDesc), len(file_iam_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_iam_proto_goTypes,
		DependencyIndexes: file_iam_proto_depIdxs,
		MessageInfos:      file_iam_proto_msgTypes,
	}.Build()
	File_iam_proto = out.File
	file_iam_proto_goTypes = nil
	file_iam_proto_depIdxs = nil
}
