// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: iam.proto

package iam_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IAMService_GetS3ApiConfiguration_FullMethodName  = "/iam_pb.IAMService/GetS3ApiConfiguration"
	IAMService_PutS3ApiConfiguration_FullMethodName  = "/iam_pb.IAMService/PutS3ApiConfiguration"
	IAMService_GetS3ApiConfigurations_FullMethodName = "/iam_pb.IAMService/GetS3ApiConfigurations"
)

// IAMServiceClient is the client API for IAMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IAMService is co-hosted on the filer gRPC port.
type IAMServiceClient interface {
	GetS3ApiConfiguration(ctx context.Context, in *GetS3ApiConfigurationRequest, opts ...grpc.CallOption) (*GetS3ApiConfigurationResponse, error)
	PutS3ApiConfiguration(ctx context.Context, in *PutS3ApiConfigurationRequest, opts ...grpc.CallOption) (*PutS3ApiConfigurationResponse, error)
	GetS3ApiConfigurations(ctx context.Context, in *GetS3ApiConfigurationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetS3ApiConfigurationsResponse], error)
}

type iAMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIAMServiceClient(cc grpc.ClientConnInterface) IAMServiceClient {
	return &iAMServiceClient{cc}
}

func (c *iAMServiceClient) GetS3ApiConfiguration(ctx context.Context, in *GetS3ApiConfigurationRequest, opts ...grpc.CallOption) (*GetS3ApiConfigurationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetS3ApiConfigurationResponse)
	err := c.cc.Invoke(ctx, IAMService_GetS3ApiConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) PutS3ApiConfiguration(ctx context.Context, in *PutS3ApiConfigurationRequest, opts ...grpc.CallOption) (*PutS3ApiConfigurationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutS3ApiConfigurationResponse)
	err := c.cc.Invoke(ctx, IAMService_PutS3ApiConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) GetS3ApiConfigurations(ctx context.Context, in *GetS3ApiConfigurationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetS3ApiConfigurationsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IAMService_ServiceDesc.Streams[0], IAMService_GetS3ApiConfigurations_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetS3ApiConfigurationsRequest, GetS3ApiConfigurationsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IAMService_GetS3ApiConfigurationsClient = grpc.ServerStreamingClient[GetS3ApiConfigurationsResponse]

// IAMServiceServer is the server API for IAMService service.
// All implementations must embed UnimplementedIAMServiceServer
// for forward compatibility.
//
// IAMService is co-hosted on the filer gRPC port.
type IAMServiceServer interface {
	GetS3ApiConfiguration(context.Context, *GetS3ApiConfigurationRequest) (*GetS3ApiConfigurationResponse, error)
	PutS3ApiConfiguration(context.Context, *PutS3ApiConfigurationRequest) (*PutS3ApiConfigurationResponse, error)
	GetS3ApiConfigurations(*GetS3ApiConfigurationsRequest, grpc.ServerStreamingServer[GetS3ApiConfigurationsResponse]) error
	mustEmbedUnimplementedIAMServiceServer()
}

// UnimplementedIAMServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIAMServiceServer struct{}

func (UnimplementedIAMServiceServer) GetS3ApiConfiguration(context.Context, *GetS3ApiConfigurationRequest) (*GetS3ApiConfigurationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetS3ApiConfiguration not implemented")
}
func (UnimplementedIAMServiceServer) PutS3ApiConfiguration(context.Context, *PutS3ApiConfigurationRequest) (*PutS3ApiConfigurationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutS3ApiConfiguration not implemented")
}
func (UnimplementedIAMServiceServer) GetS3ApiConfigurations(*GetS3ApiConfigurationsRequest, grpc.ServerStreamingServer[GetS3ApiConfigurationsResponse]) error {
	return status.Error(codes.Unimplemented, "method GetS3ApiConfigurations not implemented")
}
func (UnimplementedIAMServiceServer) mustEmbedUnimplementedIAMServiceServer() {}
func (UnimplementedIAMServiceServer) testEmbeddedByValue()                    {}

// UnsafeIAMServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IAMServiceServer will
// result in compilation errors.
type UnsafeIAMServiceServer interface {
	mustEmbedUnimplementedIAMServiceServer()
}

func RegisterIAMServiceServer(s grpc.ServiceRegistrar, srv IAMServiceServer) {
	// If the following call panics, it indicates UnimplementedIAMServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IAMService_ServiceDesc, srv)
}

func _IAMService_GetS3ApiConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetS3ApiConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).GetS3ApiConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_GetS3ApiConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).GetS3ApiConfiguration(ctx, req.(*GetS3ApiConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_PutS3ApiConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutS3ApiConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).PutS3ApiConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_PutS3ApiConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).PutS3ApiConfiguration(ctx, req.(*PutS3ApiConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_GetS3ApiConfigurations_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetS3ApiConfigurationsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IAMServiceServer).GetS3ApiConfigurations(m, &grpc.GenericServerStream[GetS3ApiConfigurationsRequest, GetS3ApiConfigurationsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IAMService_GetS3ApiConfigurationsServer = grpc.ServerStreamingServer[GetS3ApiConfigurationsResponse]

// IAMService_ServiceDesc is the grpc.ServiceDesc for IAMService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IAMService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iam_pb.IAMService",
	HandlerType: (*IAMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetS3ApiConfiguration",
			Handler:    _IAMService_GetS3ApiConfiguration_Handler,
		},
		{
			MethodName: "PutS3ApiConfiguration",
			Handler:    _IAMService_PutS3ApiConfiguration_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetS3ApiConfigurations",
			Handler:       _IAMService_GetS3ApiConfigurations_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "iam.proto",
}
